Repository microsoft/CCF, pull requests merged in 2020-04, with the labels that each got.

#1035 Keep PR up-to-date and merge automatically
  .github/workflows/automerge.yml
Labels: automerge, sync

#1032 Key shares and consortium update
  samples/apps/txregulator/tests/txregulatorclient.py
  src/enclave/interface.h
  src/host/main.cpp
  src/lua_interp/tx_script_runner.h
  src/node/config.h
  src/node/entities.h
  src/node/genesis_gen.h
  src/node/members.h
  src/node/network_state.h
  src/node/network_tables.h
  src/node/node_state.h
  src/node/quote.h
  src/node/rpc/member_frontend.h
  src/node/rpc/node_call_types.h
  src/node/rpc/serialization.h
  src/node/rpc/test/member_voting_test.cpp
  src/node/rpc/test/node_stub.h
  src/node/rpc/user_frontend.h
  src/node/share_manager.h
  src/runtime_config/default_whitelists.h
  tests/code_update.py
  tests/e2e_logging.py
  tests/governance_history.py
  tests/infra/ccf.py
  tests/infra/consortium.py
  tests/infra/member.py
  tests/infra/proposal.py
  tests/infra/proposal_state.py
  tests/memberclient.py
  tests/recovery.py
  tests/rekey.py
Labels: sync

#1040 Remove automerge.
  .github/workflows/automerge.yml
Labels: sync

#1027 The rest of the daily build
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/publish_build.yml
  .daily.yml
  CMakeLists.txt
  cmake/common.cmake
  docker/Dockerfile
  tests/e2e_suite.py
  tests/infra/ccf.py
  tests/suite/test_suite.py
  tests/tlstest.py
Labels: sync

#1056 fix no_wait
  samples/perf_client/perf_client.h
Labels: bug
