Repository microsoft/CCF, pull requests merged in 2021-08, with the labels that each got.

#2861 Remove Forum sample app (1.x)
  CMakeLists.txt
  doc/build_apps/auth/index.rst
  doc/build_apps/auth/jwt.rst
  doc/build_apps/auth/jwt_ms_example.rst
  doc/build_apps/js_app.rst
  doc/build_apps/js_app_bundle.rst
  doc/build_apps/js_app_tsoa.rst
  doc/design_ts.md
  doc/spelling_wordlist.txt
  samples/apps/forum/.gitignore
  samples/apps/forum/README.md
  samples/apps/forum/app.tmpl.json
  samples/apps/forum/ci.sh
  samples/apps/forum/demo/generate-jwts.ts
  samples/apps/forum/demo/generate-opinions.py
  samples/apps/forum/demo/polls.csv
  samples/apps/forum/demo/start.ts
  samples/apps/forum/demo/submit-opinions.ts
  samples/apps/forum/package.json
  samples/apps/forum/rollup.config.js
  samples/apps/forum/src/authentication.ts
  samples/apps/forum/src/constants.ts
  samples/apps/forum/src/controllers/csv.ts
  samples/apps/forum/src/controllers/poll.ts
  samples/apps/forum/src/controllers/site.ts
  samples/apps/forum/src/error_handler.ts
  samples/apps/forum/src/models/poll.ts
  samples/apps/forum/src/services/csv.ts
  samples/apps/forum/src/services/poll.ts
  samples/apps/forum/test/e2e/api.test.ts
  samples/apps/forum/test/e2e/util.ts
  samples/apps/forum/test/unit/csvService.test.ts
  samples/apps/forum/test/unit/pollService.test.ts
  samples/apps/forum/test/unit/setup.ts
  samples/apps/forum/tsconfig.json
  samples/apps/forum/tsoa-support/postprocess.js
  samples/apps/forum/tsoa-support/routes.ts.tmpl
  samples/apps/forum/tsoa.json
Labels: lts

#2860 Remove Forum sample app
  CHANGELOG.md
  CMakeLists.txt
  doc/build_apps/auth/index.rst
  doc/build_apps/auth/jwt.rst
  doc/build_apps/auth/jwt_ms_example.rst
  doc/build_apps/js_app.rst
  doc/build_apps/js_app_bundle.rst
  doc/build_apps/js_app_tsoa.rst
  doc/design_ts.md
  doc/spelling_wordlist.txt
  samples/apps/forum/.gitignore
  samples/apps/forum/README.md
  samples/apps/forum/app.tmpl.json
  samples/apps/forum/ci.sh
  samples/apps/forum/demo/generate-jwts.ts
  samples/apps/forum/demo/generate-opinions.py
  samples/apps/forum/demo/polls.csv
  samples/apps/forum/demo/start.ts
  samples/apps/forum/demo/submit-opinions.ts
  samples/apps/forum/package.json
  samples/apps/forum/rollup.config.js
  samples/apps/forum/src/authentication.ts
  samples/apps/forum/src/constants.ts
  samples/apps/forum/src/controllers/csv.ts
  samples/apps/forum/src/controllers/poll.ts
  samples/apps/forum/src/controllers/site.ts
  samples/apps/forum/src/error_handler.ts
  samples/apps/forum/src/models/poll.ts
  samples/apps/forum/src/services/csv.ts
  samples/apps/forum/src/services/poll.ts
  samples/apps/forum/test/e2e/api.test.ts
  samples/apps/forum/test/e2e/util.ts
  samples/apps/forum/test/unit/csvService.test.ts
  samples/apps/forum/test/unit/pollService.test.ts
  samples/apps/forum/test/unit/setup.ts
  samples/apps/forum/tsconfig.json
  samples/apps/forum/tsoa-support/postprocess.js
  samples/apps/forum/tsoa-support/routes.ts.tmpl
  samples/apps/forum/tsoa.json
Labels: lts-candidate

#2858 Backport new `/node/version` endpoint to 1.x LTS
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  doc/schemas/node_openapi.json
  python/setup.py
  python/version.py.in
  samples/apps/logging/logging.cpp
  src/common/version.h.in
  src/enclave/main.cpp
  src/endpoints/common_endpoint_registry.cpp
  src/host/enclave.h
  src/host/main.cpp
  src/node/rpc/call_types.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  tests/reconfiguration.py
  tests/test_install_build.sh
Labels: lts

#2852 Raft committable suffix: efficient backtracking to find safe matching index
  CMakeLists.txt
  src/consensus/aft/impl/state.h
  src/consensus/aft/raft.h
  src/consensus/aft/raft_types.h
  src/consensus/aft/test/committable_suffix.cpp
  src/consensus/aft/test/main.cpp
  src/consensus/aft/test/test_common.h
Labels: lts-candidate

#2879 Fix reported `TxID` term during public recovery
  src/crypto/symmetric_key.h
  src/kv/deserialise.h
  src/kv/encryptor.h
  src/kv/generic_serialise_wrapper.h
  src/kv/kv_types.h
  src/kv/test/null_encryptor.h
Labels: 1.x-todo

#2878 Cherry-pick #2849 to LTS 1.x
  src/node/rpc/frontend.h
Labels: 1.x-backport

#2883 Port 1ES pool pipeline to 1.x LTS (#2811, #2867, #2871, #2872, #2873, #2880)
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/publish_zap_report.yml
  .azure-pipelines-templates/stress-matrix.yml
  .multi-thread.yml
  .nodes.sh
  CMakeLists.txt
  src/apps/tpcc/tpcc.cmake
  src/node/progress_tracker_types.h
  src/node/test/progress_tracker.cpp
  tests/zap.config
  tests/zap.py
Labels: 1.x-backport

#2881 Cherry-pick #2879 to 1.x LTS
  CHANGELOG.md
  src/crypto/symmetric_key.h
  src/kv/deserialise.h
  src/kv/encryptor.h
  src/kv/generic_serialise_wrapper.h
  src/kv/kv_types.h
  src/kv/test/null_encryptor.h
Labels: 1.x-backport

#2888 Remove use of GithHub API for `lts_compatibility` test
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/common.yml
  tests/infra/github.py
  tests/lts_compatibility.py
  tests/requirements.txt
Labels: 1.x-todo

#2895 Cherry-pick #2888 to 1.x LTS
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/common.yml
  tests/infra/github.py
  tests/lts_compatibility.py
  tests/requirements.txt
Labels: 1.x-backport

#2894 Report HTTP signature parsing error to client
  src/http/authentication/sig_auth.h
  src/http/http_sig.h
  src/http/test/http_test.cpp
  tests/governance.py
Labels: 1.x-todo
