Repository microsoft/CCF, pull requests merged in 2022-12, with the labels that each got.

#4663 Add a UBSan suppression for QCBOR.
  src/ubsan.suppressions
Labels: auto-backport, 3.x-todo

#4658 Bias random simulation to forward-progress actions.
  tla/.gitignore
  tla/SIMCoverageccfraft.R
  tla/SIMCoverageccfraft.cfg
  tla/SIMCoverageccfraft.tla
  tla/SIMccfraft.tla
Labels: tla

#4682 Remove elements from map outside of loop.
  .devcontainer/devcontainer.json
  .vscode/launch.json
  src/consensus/aft/test/logging_stub.h
Labels: testing

#4677 Document read-write KV restrictions in different execution contexts
  doc/audit/index.rst
  doc/audit/read_write_restrictions.rst
  doc/build_apps/kv/kv_how_to.rst
  include/ccf/kv/map_handle.h
  include/ccf/kv/untyped_map_handle.h
  src/js/test/js.cpp
  src/js/wrap.cpp
  src/js/wrap.h
  src/kv/untyped_map_handle.cpp
  tests/governance.py
  tests/governance_js.py
  tests/infra/consortium.py
  tests/infra/proposal.py
Labels: auto-backport, 3.x-todo

#4676 Add wrappers for additional gov tables
  .daily_canary
  .snpcc_canary
  doc/schemas/gov_openapi.json
  src/node/rpc/member_frontend.h
  src/service/network_tables.h
Labels: auto-backport, 3.x-todo

#4695 Add precise error message when recovery threshold is greater than number of recovery members
  src/node/share_manager.h
Labels: auto-backport, 3.x-todo

#4704 Fix compilation error with undefined variables in SNP builds
  .snpcc_canary
  include/ccf/pal/attestation.h
  include/ccf/pal/attestation_sev_snp.h
  include/ccf/pal/attestation_sgx.h
  include/ccf/service/code_digest.h
Labels: auto-backport, 3.x-todo

#4723 Log certificates used for node-to-node peer certificate failures
  src/node/channels.h
  src/node/node_to_node_channel_manager.h
  src/node/test/channels.cpp
Labels: 2.x-todo, auto-backport, 3.x-todo

#4718 Offline cose sign1 signing
  doc/governance/hsm_keys.rst
  python/ccf/cose.py
  python/setup.py
Labels: auto-backport, 3.x-todo

#4721 Restore SIG_IGN handler
  doc/operations/troubleshooting.rst
  src/host/main.cpp
Labels: auto-backport, 3.x-todo

#4717 Enable `TCP_NODELAY` for all TCP connections
  CHANGELOG.md
  src/host/tcp.h
Labels: auto-backport, 3.x-todo

#4736 [release/3.x] Cherry pick: Offline cose sign1 signing (#4718)
  doc/governance/hsm_keys.rst
  python/ccf/cose.py
  python/setup.py
Labels: 3.x-backport

#4733 Remove unintended time checks from node-to-node validation
  CHANGELOG.md
  include/ccf/crypto/verifier.h
  src/kv/test/kv_snapshot.cpp
  src/node/channels.h
  src/node/test/channels.cpp
  tests/infra/clients.py
  tests/infra/node.py
  tests/partitions_test.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4740 [release/3.x] Cherry pick: Remove unintended time checks from node-to-node validation (#4733)
  CHANGELOG.md
  include/ccf/crypto/verifier.h
  src/kv/test/kv_snapshot.cpp
  src/node/channels.h
  src/node/test/channels.cpp
  tests/infra/clients.py
  tests/infra/node.py
  tests/partitions_test.py
Labels: 3.x-backport

#4739 [release/2.x] Cherry pick: Remove unintended time checks from node-to-node validation (#4733)
  CHANGELOG.md
  include/ccf/crypto/verifier.h
  src/node/channels.h
  src/node/test/channels.cpp
  tests/infra/clients.py
  tests/infra/node.py
  tests/partitions_test.py
Labels: 2.x-backport

#4741 Update minimum view on partition test
  tests/partitions_test.py
Labels: 2.x-backport, auto-backport, 3.x-backport

#4730 Fix issues with snapshot generation for CHAMP
  .daily_canary
  CHANGELOG.md
  include/ccf/ds/logger.h
  src/ds/champ_map.h
  src/ds/map_serializers.h
  src/ds/rb_map.h
  src/ds/test/map_test.cpp
  src/kv/test/kv_snapshot.cpp
  src/kv/untyped_map.h
  tests/partitions_test.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4746 Partition test fix
  tests/partitions_test.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4748 [release/3.x] Cherry pick: Fix issues with snapshot generation for CHAMP (#4730)
  CHANGELOG.md
  include/ccf/ds/logger.h
  src/ds/champ_map.h
  src/ds/map_serializers.h
  src/ds/rb_map.h
  src/ds/test/map_test.cpp
  src/kv/test/kv_snapshot.cpp
  src/kv/untyped_map.h
  tests/partitions_test.py
Labels: 3.x-backport

#4747 [release/2.x] Cherry pick: Fix issues with snapshot generation for CHAMP (#4730)
  .daily_canary
  CHANGELOG.md
  include/ccf/ds/logger.h
  src/ds/champ_map.h
  src/ds/map_serializers.h
  src/ds/rb_map.h
  src/ds/test/map_test.cpp
  src/kv/untyped_map.h
  tests/partitions_test.py
Labels: 2.x-backport

#4755 Docs: Fix broken SGX link
  doc/overview/glossary.rst
Labels: auto-backport, 3.x-todo

#4770 [release/3.x] Cherry pick: Increase NumHeapPages for js_generic (#4759)
  CHANGELOG.md
  src/apps/js_generic/oe_sign.conf
Labels: 3.x-backport

#4762 Fix recording of node_data in KV for Start nodes
  CHANGELOG.md
  src/host/main.cpp
  src/node/rpc/node_frontend.h
  tests/governance.py
  tests/infra/network.py
  tests/recovery.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4773 [release/2.x] Cherry pick: Fix recording of node_data in KV for Start nodes (#4762)
  CHANGELOG.md
  src/host/main.cpp
  src/node/rpc/node_frontend.h
  tests/governance.py
  tests/infra/network.py
  tests/recovery.py
Labels: 2.x-backport

#4774 [release/3.x] Cherry pick: Fix recording of node_data in KV for Start nodes (#4762)
  CHANGELOG.md
  src/host/main.cpp
  src/node/rpc/node_frontend.h
  tests/governance.py
  tests/infra/network.py
  tests/recovery.py
Labels: 3.x-backport

#4703 Enable a Scan Build job in Daily
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/scan_build.yml
  scripts/scan-build.sh
  src/crypto/openssl/base64.h
  src/crypto/openssl/key_pair.cpp
  src/ds/test/messaging.cpp
  src/host/test/ledger.cpp
  src/js/wrap.cpp
  src/node/acme_client.h
  src/node/rpc/node_frontend.h
Labels: auto-backport, 3.x-todo
