Repository microsoft/CCF, pull requests merged in 2022-11, with the labels that each got.

#4436 Minor refactorings of TLA+ spec
  tla/ccfraft.tla
Labels: tla

#4437 No need to intersect with config_server if agree_server is defined in… … terms of config_server.
  tla/ccfraft.tla
Labels: tla

#4439 Remove unused variable votesSent.
  tla/ccfraft.tla
Labels: tla

#4487 [release/2.x] Cherry pick: Use new IceLake SGX pool for Azure DevOps (#4440)
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/stress-matrix.yml
  .multi-thread.yml
Labels: 2.x-backport

#4470 Remember node and log index instead of having TLC hang on to a copy of a prefix of some node's log.
  tla/ccfraft.tla
Labels: tla

#4471 Exclude messagesSent variable s.t. two states are considered equal if they only differ in the number of messages sent.
  tla/MCccfraft.cfg
  tla/MCccfraft.tla
  tla/MCccfraftWithReconfig.tla
Labels: tla

#4490 Infra: fix for new Debian package name for 3.x releases
  .daily_canary
  tests/infra/github.py
  tests/lts_compatibility.py
Labels: auto-backport, 3.x-todo

#4485 In TLA+ spec, Raft leader should only advance its commit index in current term
  tla/ccfraft.tla
Labels: tla

#4515 Explicitly add `libsgx-dcap-ql-dev` to PSW
  getting_started/setup_vm/roles/intel/vars/common.yml
Labels: 2.x-todo, auto-backport

#4514 Move ring buffer bound check early
  src/enclave/main.cpp
Labels: 2.x-todo, auto-backport, 3.x-todo

#4510 Upgrade Open Enclave from 0.18.2 to 0.18.4
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
Labels: 2.x-todo, auto-backport, 3.x-todo

#4520 [release/2.x] Cherry pick: Move ring buffer bound check early (#4514)
  src/enclave/main.cpp
Labels: 2.x-backport

#4488 [release/2.x] Remove explicit IceLakeSGX job
  .azure-pipelines-templates/daily-matrix.yml
  .daily_canary
Labels: 2.x-backport

#4525 Fix get_latest_public_state() when used on incomplete ledgers
  python/ccf/ledger.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4529 Update ci-checks to use gha fold output
  scripts/ci-checks.sh
Labels: ci

#4531 [release/2.x] Cherry pick: Upgrade Open Enclave from 0.18.2 to 0.18.4 (#4510)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/ccf_app.cmake
  cmake/cpack_settings.cmake
Labels: 2.x-backport

#4535 [release/2.x] Cherry pick: Download Doxygen from SourceForge to keep v1.9.4 (#4432)
  .azure-pipelines-templates/install_deb.yml
  getting_started/setup_vm/roles/ccf_build/vars/common.yml
Labels: 2.x-backport

#4534 Forwarded request's actor fix
  .daily_canary
  src/node/rpc/forwarder.h
  tests/e2e_logging.py
  tests/infra/logging_app.py
Labels: auto-backport, 3.x-todo

#4552 Simulate ccfraft spec with TLC for five nodes...
  tla/SIMccfraft.cfg
  tla/SIMccfraft.tla
Labels: tla

#4562 Only run SNP CI on push on release branches
  .azure_pipelines_snpcc.yml
Labels: auto-backport, 3.x-todo

#4564 Update t_cose to version 1.1.
  .daily_canary
  3rdparty/exported/t_cose/CMakeLists.txt
  3rdparty/exported/t_cose/Makefile.ossl
  3rdparty/exported/t_cose/Makefile.psa
  3rdparty/exported/t_cose/Makefile.test
  3rdparty/exported/t_cose/README.md
  3rdparty/exported/t_cose/crypto_adapters/t_cose_openssl_crypto.c
  3rdparty/exported/t_cose/crypto_adapters/t_cose_psa_crypto.c
  3rdparty/exported/t_cose/crypto_adapters/t_cose_test_crypto.c
  3rdparty/exported/t_cose/examples/t_cose_basic_example_ossl.c
  3rdparty/exported/t_cose/examples/t_cose_basic_example_psa.c
  3rdparty/exported/t_cose/inc/t_cose/q_useful_buf.h
  3rdparty/exported/t_cose/inc/t_cose/t_cose_common.h
  3rdparty/exported/t_cose/inc/t_cose/t_cose_sign1_sign.h
  3rdparty/exported/t_cose/inc/t_cose/t_cose_sign1_verify.h
  3rdparty/exported/t_cose/src/t_cose_crypto.h
  3rdparty/exported/t_cose/src/t_cose_short_circuit.c
  3rdparty/exported/t_cose/src/t_cose_short_circuit.h
  3rdparty/exported/t_cose/src/t_cose_sign1_sign.c
  3rdparty/exported/t_cose/src/t_cose_sign1_verify.c
  3rdparty/exported/t_cose/src/t_cose_standard_constants.h
  3rdparty/exported/t_cose/src/t_cose_util.c
  3rdparty/exported/t_cose/src/t_cose_util.h
  3rdparty/exported/t_cose/t_cose.xcodeproj/project.pbxproj
  3rdparty/exported/t_cose/test/run_tests.c
  3rdparty/exported/t_cose/test/t_cose_make_openssl_test_key.c
  3rdparty/exported/t_cose/test/t_cose_make_psa_test_key.c
  3rdparty/exported/t_cose/test/t_cose_make_test_messages.c
  3rdparty/exported/t_cose/test/t_cose_make_test_pub_key.h
  3rdparty/exported/t_cose/test/t_cose_rsa_test_key.h
  3rdparty/exported/t_cose/test/t_cose_sign_verify_test.c
  3rdparty/exported/t_cose/test/t_cose_sign_verify_test.h
  3rdparty/exported/t_cose/test/t_cose_test.c
  3rdparty/exported/t_cose/test/t_cose_test.h
  cgmanifest.json
  cmake/t_cose.cmake
Labels: auto-backport, 3.x-todo

#4566 Pass startup snapshot separately from configuration
  .daily_canary
  CHANGELOG.md
  edl/ccf.edl
  include/ccf/node/startup_config.h
  src/common/configuration.h
  src/enclave/enclave.h
  src/enclave/main.cpp
  src/enclave/virtual_enclave.h
  src/host/enclave.h
  src/host/main.cpp
  src/node/node_state.h
Labels: 2.x-todo, auto-backport, 3.x-todo

#4567 Fix installing virtual and sgx together
  .daily_canary
  Makefile
  cmake/cpack_settings.cmake
Labels: auto-backport, 3.x-todo

#4571 [release/2.x] Cherry pick: Pass startup snapshot separately from configuration (#4566)
  CHANGELOG.md
  edl/ccf.edl
  src/common/configuration.h
  src/enclave/enclave.h
  src/enclave/main.cpp
  src/enclave/virtual_enclave.h
  src/host/enclave.h
  src/host/main.cpp
  src/node/node_state.h
Labels: 2.x-backport

#4575 Try to get the correct group ID
  .azure-pipelines-templates/platform.yml
Labels: 2.x-todo, auto-backport, 3.x-todo

#4577 [release/2.x] Cherry pick: Try to get the correct group ID (#4575)
  .azure-pipelines-templates/cmake.yml
Labels: 2.x-backport

#4506 Add ccf_cose_sign1 CLI tool
  CHANGELOG.md
  doc/governance/accept_recovery.rst
  doc/governance/adding_member.rst
  doc/governance/common_member_operations.rst
  doc/governance/open_network.rst
  doc/governance/proposals.rst
  doc/use_apps/issue_commands.rst
  python/ccf/cose.py
  python/requirements.txt
  python/setup.py
  scripts/ci-checks.sh
  tests/governance.py
  tests/governance_history.py
  tests/infra/clients.py
  tests/infra/signing.py
  tests/requirements.txt
  tests/sandbox/sandbox.sh
Labels: auto-backport, 3.x-todo

#4586 [release/3.x] Cherry pick: Upgrade Open Enclave from 0.18.2 to 0.18.4 (#4510)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
Labels: 3.x-backport

#4588 [release/3.x] Cherry pick: Add ccf_cose_sign1 CLI tool (#4506)
  CHANGELOG.md
  doc/governance/accept_recovery.rst
  doc/governance/adding_member.rst
  doc/governance/common_member_operations.rst
  doc/governance/open_network.rst
  doc/governance/proposals.rst
  doc/use_apps/issue_commands.rst
  python/ccf/cose.py
  python/ccf/ledger_viz.py
  python/requirements.txt
  python/setup.py
  tests/governance.py
  tests/governance_history.py
  tests/infra/clients.py
  tests/infra/signing.py
  tests/requirements.txt
  tests/sandbox/sandbox.sh
Labels: 3.x-backport

#4590 [release/3.x] Cherry pick: Decorate and identify SNP libraries (#4569)
  .cmake-format.py
  .daily_canary
  .snpcc_canary
  CHANGELOG.md
  CMakeLists.txt
  cmake/ccf_app.cmake
  cmake/common.cmake
  cmake/crypto.cmake
  cmake/nghttp2.cmake
  cmake/protobuf.cmake
  cmake/qcbor.cmake
  cmake/quickjs.cmake
  cmake/sss.cmake
  cmake/t_cose.cmake
  doc/host_config_schema/cchost_config.json
  samples/config/join_config.json
  samples/config/minimal_config.json
  samples/config/recover_config.json
  samples/config/start_config.json
  src/apps/external_executor/CMakeLists.txt
  src/host/configuration.h
  src/host/enclave.h
  src/host/main.cpp
  tests/code_update.py
  tests/config.jinja
  tests/governance.py
  tests/infra/e2e_args.py
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/path.py
  tests/infra/remote.py
  tests/infra/utils.py
  tests/js-modules/modules.py
  tests/jwt_test.py
  tests/lts_compatibility.py
  tests/nobuiltins.py
  tests/reconfiguration.py
  tests/sandbox/sandbox.sh
  tests/start_network.py
Labels: 3.x-backport

#4589 Fix for `raft_test` failure
  src/consensus/aft/raft.h
  src/consensus/aft/test/committable_suffix.cpp
  src/consensus/aft/test/main.cpp
Labels: auto-backport, 3.x-todo

#4595 Session consistency: Parse forwarded messages with consistency info
  .daily_canary
  CHANGELOG.md
  include/ccf/odata_error.h
  include/ccf/rpc_context.h
  src/consensus/aft/raft.h
  src/enclave/forwarder_types.h
  src/enclave/rpc_sessions.h
  src/enclave/session.h
  src/enclave/tls_session.h
  src/http/http2_session.h
  src/http/http_session.h
  src/kv/kv_types.h
  src/kv/test/stub_consensus.h
  src/node/node_types.h
  src/node/rpc/forwarder.h
  src/node/rpc/frontend.h
  src/node/rpc/rpc_context_impl.h
  src/quic/quic_session.h
  tests/e2e_tutorial.py
  tests/infra/clients.py
  tests/infra/commit.py
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/infra/node.py
  tests/lts_compatibility.py
  tests/partitions_test.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4600 Cherry-pick #4567 to 3.x LTS
  .daily_canary
  Makefile
  cmake/cpack_settings.cmake
Labels: 3.x-backport

#4596 `sandbox.sh`: Set default value for platform
  tests/sandbox/sandbox.sh
Labels: auto-backport, 3.x-todo

#4607 Fix containers and PyPi release workflows
  .github/workflows/containers.yml
  .github/workflows/pypi.yml
  getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
Labels: auto-backport, 3.x-backport

#4606 [release/2.x] Cherry pick: Session consistency: Parse forwarded messages with consistency info (#4595)
  include/ccf/odata_error.h
  include/ccf/rpc_context.h
  src/enclave/forwarder_types.h
  src/enclave/rpc_sessions.h
  src/node/node_types.h
  src/node/rpc/forwarder.h
  src/node/rpc/rpc_context_impl.h
  tests/e2e_tutorial.py
  tests/infra/clients.py
  tests/infra/commit.py
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/infra/node.py
  tests/lts_compatibility.py
  tests/partitions_test.py
Labels: 2.x-backport

#4613 [release/3.x] Cherry pick: Fix containers and PyPi release workflows (#4607)
  .github/workflows/containers.yml
  .github/workflows/pypi.yml
  getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
Labels: 3.x-backport

#4598 Re-enable COSE tests in suite
  .daily_canary
  tests/governance.py
  tests/governance_history.py
  tests/suite/test_suite.py
Labels: auto-backport, 3.x-todo

#4597 Re-enable Vegeta tests on SNP
  .snpcc_canary
  tests/vegeta_stress.py
Labels: auto-backport, 3.x-todo

#4611 Session Consistency: Turn on enforcement of session consistency across elections
  src/node/rpc/forwarder.h
  tests/partitions_test.py
Labels: auto-backport, 3.x-todo

#4617 Misc test fixes
  .daily_canary
  tests/governance.py
  tests/infra/log_capture.py
Labels: auto-backport, 3.x-todo

#4623 Fix spurious election in partition test
  .daily_canary
  tests/partitions_test.py
Labels: auto-backport, 3.x-todo

#4628 Amend sandbox.sh to define where the constitution files are
  tests/sandbox/sandbox.sh
Labels: auto-backport, 3.x-todo

#4642 Fix doc links and warnings
  doc/conf.py
  doc/use_apps/issue_commands.rst
Labels: auto-backport, 3.x-todo

#4653 Add comments for spec constants.
  tla/ccfraft.tla
Labels: tla

#4655 Check for deadlocks when simulating the spec without state- or action…
  tla/SIMccfraft.cfg
Labels: tla

#4661 Point to TLA+ documentation that doesn't confuse learners with PlusCal.
  doc/architecture/raft_tla.rst
Labels: tla

#4533 Add workflow for TLA+ checking
  .github/workflows/tlaplus.yml
Labels: tla
