Repository microsoft/CCF, pull requests merged in 2022-06, with the labels that each got.

#3910 [release/2.x] Cherry pick: Shutdown new joining node early if target service certificate is invalid (#3895)
  CHANGELOG.md
  src/enclave/client_endpoint.h
  src/enclave/tls_endpoint.h
  src/http/http_endpoint.h
  src/node/node_state.h
  tests/config.jinja
  tests/infra/network.py
  tests/infra/remote.py
  tests/reconfiguration.py
Labels: 2.x-backport

#3880 Add endpoint to get previous service identity
  .daily_canary
  CHANGELOG.md
  doc/audit/builtin_maps.rst
  doc/schemas/node_openapi.json
  src/enclave/enclave.h
  src/enclave/main.cpp
  src/node/historical_queries_adapter.cpp
  src/node/node_state.h
  src/node/rpc/network_identity_interface.h
  src/node/rpc/node_frontend.h
  src/service/genesis_gen.h
  src/service/network_tables.h
  src/service/tables/previous_service_identity.h
  tests/infra/network.py
  tests/lts_compatibility.py
  tests/recovery.py
  tests/start_network.py
  tests/suite/test_suite.py
Labels: 2.x-todo

#3913 [LTS 2.x] Cherry pick `/node/network/previous_identity` (#3880) to 2.x LTS
  CHANGELOG.md
  doc/audit/builtin_maps.rst
  doc/schemas/node_openapi.json
  src/enclave/enclave.h
  src/enclave/main.cpp
  src/node/historical_queries_adapter.cpp
  src/node/node_state.h
  src/node/rpc/network_identity_interface.h
  src/node/rpc/node_frontend.h
  src/service/genesis_gen.h
  src/service/network_tables.h
  src/service/tables/previous_service_identity.h
  tests/infra/network.py
  tests/lts_compatibility.py
  tests/recovery.py
  tests/start_network.py
  tests/suite/test_suite.py
Labels: 2.x-backport

#3917 Infra: make ledger file copy more resilient
  .daily_canary
  .pylintrc
  tests/infra/remote.py
Labels: 2.x-todo, auto-backport

#3921 Update to build image to PSW 2.16.100
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines-v8.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
Labels: 2.x-todo, auto-backport

#3923 [release/2.x] Cherry pick: Update to build image to PSW 2.16.100 (#3921)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-v8.yml
  .azure-pipelines.yml
  .daily.yml
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
Labels: 2.x-backport

#3924 Infra: Fix node in container setup CI
  .daily_canary
  tests/infra/github.py
  tests/infra/remote_shim.py
  tests/lts_compatibility.py
Labels: 2.x-backport, auto-backport

#3922 [release/2.x] Cherry pick: PSW update to 2.16.100 (#3920)
  CHANGELOG.md
  docker/app_dev
  docker/app_run
  docker/ccf_ci
Labels: 2.x-backport

#3932 [release/2.x] Cherry pick: Fix rename properly (#3930)
  .azure-pipelines-templates/release.yml
Labels: 2.x-backport

#3933 [release/2.x] Cherry pick: Unsafe different project (#3894)
  .azure-pipelines-templates/install_deb.yml
  CMakeLists.txt
  cmake/ccf_unsafe-config.cmake.in
  cmake/cpack_settings.cmake
  cmake/version.cmake
  samples/apps/logging/CMakeLists.txt
  tests/test_install_build.sh
Labels: 2.x-backport

#3939 Upgrade to Open Enclave 0.18.0
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-v8.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/ccf_app.cmake
  cmake/cpack_settings.cmake
  src/ds/ccf_memcpy.h
  src/ds/ring_buffer.h
  src/enclave/enclave.h
Labels: 2.x-backport

#3934 Prepare release notes for 2.0.1
  CHANGELOG.md
Labels: 2.x-backport

#3953 Remove use of `SIG_IGN` for `SIGPIPE`
  .daily_canary
  src/host/main.cpp
Labels: 2.x-todo, auto-backport

#3935 Describe forwarding behaviour in generated OpenAPI
  .daily_canary
  CHANGELOG.md
  doc/schemas/app_openapi.json
  doc/schemas/gov_openapi.json
  doc/schemas/node_openapi.json
  include/ccf/ds/openapi.h
  include/ccf/endpoint.h
  samples/apps/logging/logging.cpp
  src/endpoints/endpoint_registry.cpp
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
Labels: 2.x-todo, auto-backport

#3931 TLS endpoint closing state
  .daily_canary
  src/enclave/tls_endpoint.h
Labels: 2.x-todo, auto-backport

#3943 Update NodeJS to v16
  getting_started/setup_vm/roles/nodejs/vars/common.yml
Labels: 2.x-todo, auto-backport

#3946 Do not append an unnecessary line return when using Json logging
  include/ccf/ds/logger.h
  src/ds/test/logger_json_test.cpp
Labels: 2.x-todo, auto-backport

#3942 Reflect unsafe status in /node/version
  CHANGELOG.md
  cmake/version.cmake
  doc/schemas/node_openapi.json
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  tests/reconfiguration.py
Labels: 2.x-todo, auto-backport

#3967 Ignore nghttp2 URLs in linkcheck
  doc/conf.py
Labels: 2.x-todo, auto-backport

#3966 [release/2.x] Cherry pick: Describe forwarding behaviour in generated OpenAPI (#3935)
  CHANGELOG.md
  doc/schemas/app_openapi.json
  doc/schemas/gov_openapi.json
  doc/schemas/node_openapi.json
  include/ccf/ds/openapi.h
  include/ccf/endpoint.h
  samples/apps/logging/logging.cpp
  src/endpoints/endpoint_registry.cpp
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
Labels: 2.x-backport

#3941 Restrict maximum size of client HTTP request
  .daily_canary
  CHANGELOG.md
  doc/generate_config_rst.py
  doc/host_config_schema/cchost_config.json
  doc/operations/certificates.rst
  doc/operations/index.rst
  doc/operations/network.rst
  doc/operations/node_output.rst
  doc/operations/resource_usage.rst
  doc/schemas/node_openapi.json
  include/ccf/ds/unit_strings.h
  include/ccf/http_configuration.h
  include/ccf/odata_error.h
  include/ccf/service/node_info_network.h
  src/common/configuration.h
  src/consensus/consensus_types.h
  src/ds/test/unit_strings.cpp
  src/enclave/rpc_sessions.h
  src/host/configuration.h
  src/http/http_endpoint.h
  src/http/http_parser.h
  src/node/rpc/node_frontend.h
  src/node/session_metrics.h
  tests/e2e_common_endpoints.py
  tests/e2e_logging.py
  tests/infra/e2e_args.py
  tests/infra/interfaces.py
  tests/suite/test_suite.py
Labels: 1.x-todo, 2.x-todo, auto-backport

#3976 [release/2.x] Cherry pick: Restrict maximum size of client HTTP request (#3941)
  .daily_canary
  CHANGELOG.md
  doc/generate_config_rst.py
  doc/host_config_schema/cchost_config.json
  doc/operations/index.rst
  doc/operations/network.rst
  doc/operations/node_output.rst
  doc/operations/resource_usage.rst
  doc/schemas/node_openapi.json
  include/ccf/ds/unit_strings.h
  include/ccf/http_configuration.h
  include/ccf/odata_error.h
  include/ccf/service/node_info_network.h
  src/common/configuration.h
  src/consensus/consensus_types.h
  src/ds/test/unit_strings.cpp
  src/enclave/rpc_sessions.h
  src/host/configuration.h
  src/http/http_endpoint.h
  src/http/http_parser.h
  src/node/session_metrics.h
  tests/e2e_common_endpoints.py
  tests/e2e_logging.py
  tests/infra/e2e_args.py
  tests/infra/interfaces.py
  tests/suite/test_suite.py
Labels: 2.x-backport

#3979 [release/2.x] Cherry pick: Reflect unsafe status in /node/version (#3942)
  CHANGELOG.md
  cmake/version.cmake
  doc/schemas/node_openapi.json
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  tests/reconfiguration.py
Labels: 2.x-backport

#3978 Use custom mutex implementation on SGX
  .threading_canary
  include/ccf/ds/mutex.h
  include/ccf/endpoint_registry.h
  src/consensus/aft/impl/state.h
  src/consensus/aft/raft.h
  src/ds/histogram.h
  src/ds/test/stub_writer.h
  src/enclave/main.cpp
  src/enclave/rpc_sessions.h
  src/endpoints/authentication/sig_auth.cpp
  src/endpoints/base_endpoint_registry.cpp
  src/endpoints/endpoint_registry.cpp
  src/host/dns.h
  src/host/ledger.h
  src/host/tcp.h
  src/host/udp.h
  src/kv/store.h
  src/kv/untyped_map.h
  src/node/acme_client.h
  src/node/historical_queries.h
  src/node/history.h
  src/node/jwt_key_auto_refresh.h
  src/node/ledger_secrets.h
  src/node/node_state.h
  src/node/node_to_node_channel_manager.h
  src/node/request_tracker.h
  src/node/rpc/frontend.h
  src/node/snapshotter.h
  src/node/test/historical_queries.cpp
Labels: 2.x-todo, auto-backport

#3980 [release/2.x] Cherry pick: Use custom mutex implementation on SGX (#3978)
  .threading_canary
  include/ccf/ds/mutex.h
  include/ccf/endpoint_registry.h
  src/consensus/aft/impl/state.h
  src/consensus/aft/raft.h
  src/ds/histogram.h
  src/ds/test/stub_writer.h
  src/enclave/main.cpp
  src/enclave/rpc_sessions.h
  src/endpoints/authentication/sig_auth.cpp
  src/endpoints/base_endpoint_registry.cpp
  src/endpoints/endpoint_registry.cpp
  src/host/dns.h
  src/host/ledger.h
  src/host/tcp.h
  src/kv/store.h
  src/kv/untyped_map.h
  src/node/historical_queries.h
  src/node/history.h
  src/node/jwt_key_auto_refresh.h
  src/node/ledger_secrets.h
  src/node/node_state.h
  src/node/node_to_node_channel_manager.h
  src/node/request_tracker.h
  src/node/rpc/frontend.h
  src/node/snapshotter.h
  src/node/test/historical_queries.cpp
Labels: 2.x-backport

#3983 Do not buffer incoming TLS frames if session is closed
  .daily_canary
  src/enclave/tls_endpoint.h
  tests/e2e_common_endpoints.py
Labels: 2.x-todo, auto-backport

#3986 Limit size of recovered ledger entries batch
  .daily_canary
  CHANGELOG.md
  python/ccf/ledger_viz.py
  src/host/ledger.h
  src/host/test/ledger.cpp
Labels: 2.x-todo, auto-backport

#3987 [release/2.x] Cherry pick: Limit size of recovered ledger entries batch (#3986)
  .daily_canary
  CHANGELOG.md
  python/ccf/ledger_viz.py
  src/host/ledger.h
  src/host/test/ledger.cpp
Labels: 2.x-backport

#3990 [release/2.x] Cherry pick: Remove null byte from PEM files (#3885)
  CHANGELOG.md
  include/ccf/crypto/pem.h
  tests/infra/consortium.py
Labels: 2.x-backport

#3971 New Raft leaders must only commit entries from the current term
  .daily_canary
  src/consensus/aft/raft.h
  src/consensus/aft/test/committable_suffix.cpp
  src/consensus/aft/test/driver.h
  src/kv/kv_types.h
  src/kv/store.h
  src/kv/test/stub_consensus.h
  src/node/history.h
  tests/lts_compatibility.py
  tests/raft_scenarios/fancy_election.1
  tests/raft_scenarios/fancy_election.2
  tests/raft_scenarios_gen.py
Labels: 2.x-todo, auto-backport

#3995 [release/2.x] Cherry pick: Track number of service recoveries (#3982)
  .daily_canary
  CHANGELOG.md
  doc/operations/recovery.rst
  doc/schemas/node_openapi.json
  include/ccf/service/tables/service.h
  src/node/rpc/call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  src/service/genesis_gen.h
  tests/infra/consortium.py
  tests/infra/network.py
  tests/infra/node.py
  tests/lts_compatibility.py
  tests/recovery.py
Labels: 2.x-backport

#3996 Report `TxID` at which current service was created
  CHANGELOG.md
  doc/schemas/node_openapi.json
  include/ccf/service/tables/service.h
  src/node/node_state.h
  src/node/rpc/call_types.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  src/node/rpc/test/frontend_test.cpp
  src/node/rpc/test/node_frontend_test.cpp
  src/node/rpc/test/proposal_id_test.cpp
  src/service/genesis_gen.h
  tests/infra/consortium.py
  tests/recovery.py
Labels: 2.x-todo, auto-backport

#3973 Add support for second read-only snapshots directory
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  doc/operations/ledger_snapshot.rst
  src/host/configuration.h
  src/host/main.cpp
  src/host/snapshots.h
  src/host/test/ledger.cpp
  tests/config.jinja
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/remote.py
  tests/reconfiguration.py
  tests/recovery.py
Labels: 2.x-todo, auto-backport

#3997 Add arbitrary service data
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  doc/operations/start_network.rst
  doc/operations/troubleshooting.rst
  doc/schemas/node_openapi.json
  include/ccf/service/tables/service.h
  src/common/configuration.h
  src/host/configuration.h
  src/host/main.cpp
  src/node/node_state.h
  src/node/rpc/call_types.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
  src/service/genesis_gen.h
  tests/config.jinja
  tests/e2e_operations.py
  tests/infra/remote.py
  tests/recovery.py
Labels: 2.x-todo, auto-backport

#4000 [release/2.x] Cherry pick: Add support for second read-only snapshots directory (#3973)
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  doc/operations/ledger_snapshot.rst
  src/host/configuration.h
  src/host/main.cpp
  src/host/snapshots.h
  src/host/test/ledger.cpp
  tests/config.jinja
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/remote.py
  tests/reconfiguration.py
  tests/recovery.py
Labels: 2.x-backport
