Repository microsoft/CCF, pull requests merged in 2022-05, with the labels that each got.

#3826 Remove duplicate lines
  src/tls/context.h
Labels: 2.x-todo

#3838 Updating URL of tla2tools in TLA+ install script
  tla/download_or_update_tla.sh
Labels: tla

#3840 Fix counting of authentication exceptions in endpoint metrics
  src/endpoints/authentication/cert_auth.cpp
  src/node/rpc/frontend.h
  src/node/rpc/test/frontend_test.cpp
Labels: 2.x-todo

#3841 [LTS 2.x] Port authn error counting fix (#3840) to 2.x
  src/endpoints/authentication/cert_auth.cpp
  src/node/rpc/frontend.h
  src/node/rpc/test/frontend_test.cpp
Labels: 2.x-backport

#3839 Rename App and CI container images
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-v8.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/ci-containers.yml
  .github/workflows/containers.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  doc/contribute/build_ccf.rst
  doc/contribute/build_images.rst
  doc/contribute/build_setup.rst
  doc/operations/run_setup.rst
Labels: 2.x-todo

#3842 Add missing \#includes
  src/enclave/forwarder_types.h
  src/enclave/rpc_handler.h
  src/enclave/rpc_sessions.h
  src/host/before_io.h
  src/host/proxy.h
  src/host/tcp.h
  src/http/http_endpoint.h
Labels: 2.x-todo

#3845 Add new JS application runtime docker image
  .github/workflows/containers.yml
  CHANGELOG.md
  getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
  getting_started/setup_vm/roles/ccf_install/vars/common.yml
Labels: 2.x-todo

#3843 [LTS 2.x] Cherry-pick #3839 to 2.x LTS
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-v8.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/ci-containers.yml
  .github/workflows/containers.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  doc/contribute/build_ccf.rst
  doc/contribute/build_images.rst
  doc/contribute/build_setup.rst
  doc/operations/run_setup.rst
Labels: 2.x-backport

#3850 [LTS 2.x] Cherry-pick #3845 to 2.x LTS
  .github/workflows/containers.yml
  CHANGELOG.md
  getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
  getting_started/setup_vm/roles/ccf_install/vars/common.yml
Labels: 2.x-backport

#3857 Fix links in `CCF 1.0 Sunset` docs section
  doc/architecture/consensus/index.rst
  doc/build_apps/release_policy.rst
Labels: 2.x-todo

#3859 [LTS 2.x] Cherry-pick #3858 to 2.x LTS
  .devcontainer/devcontainer.json
  doc/contribute/build_images.rst
  doc/contribute/build_setup.rst
  doc/operations/run_setup.rst
Labels: 2.x-backport

#3860 Correct RC version detection in Python infra
  .daily_canary
  tests/infra/node.py
Labels: 2.x-todo

#3862 [LTS 2.x] Cherry-pick RC version fix #3860 to 2.x LTS
  .daily_canary
  tests/infra/node.py
Labels: 2.x-backport

#3866 Log exceptions thrown during enclave init
  src/enclave/main.cpp
  src/indexing/strategies/seqnos_by_key_bucketed.cpp
Labels: 2.x-todo

#3883 Fix cmake install prefix
  CMakeLists.txt
Labels: 2.x-todo

#3890 Deprecate set execute outside consensus
  CHANGELOG.md
  include/ccf/endpoint.h
  samples/apps/logging/logging.cpp
  samples/apps/nobuiltins/nobuiltins.cpp
  src/endpoints/common_endpoint_registry.cpp
  src/endpoints/endpoint_registry.cpp
  src/node/rpc/node_frontend.h
  tests/js-launch-host-process/app.json
  tests/npm-app/app.json
Labels: 2.x-backport

#3892 Add log line for when ledger entry cannot be found
  .daily_canary
  cmake/common.cmake
  python/ccf/ledger.py
  src/host/ledger.h
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/reconfiguration.py
Labels: 2.x-todo
