Repository microsoft/CCF, pull requests merged in 2023-09, with the labels that each got.

#5608 Update `QCBOR` from `1.1` to `1.2`
  3rdparty/exported/QCBOR/CMakeLists.txt
  3rdparty/exported/QCBOR/Makefile
  3rdparty/exported/QCBOR/README.md
  3rdparty/exported/QCBOR/example.c
  3rdparty/exported/QCBOR/qcbor/UsefulBuf.h
  3rdparty/exported/QCBOR/qcbor/qcbor_common.h
  3rdparty/exported/QCBOR/qcbor/qcbor_decode.h
  3rdparty/exported/QCBOR/qcbor/qcbor_spiffy_decode.h
  3rdparty/exported/QCBOR/src/UsefulBuf.c
  3rdparty/exported/QCBOR/src/qcbor_decode.c
  3rdparty/exported/QCBOR/src/qcbor_encode.c
  3rdparty/exported/QCBOR/test/CMakeLists.txt
  3rdparty/exported/QCBOR/test/UsefulBuf_Tests.c
  3rdparty/exported/QCBOR/test/float_tests.c
  3rdparty/exported/QCBOR/test/not_well_formed_cbor.h
  3rdparty/exported/QCBOR/test/qcbor_decode_tests.c
  3rdparty/exported/QCBOR/test/qcbor_encode_tests.c
  3rdparty/exported/QCBOR/test/run_tests.c
  3rdparty/exported/QCBOR/ub-example.c
  CHANGELOG.md
  cgmanifest.json
Labels: auto-backport, 4.x-todo

#5605 Update `fmt` library from `9.1.0` to `10.1.1`
  3rdparty/exported/fmt/args.h
  3rdparty/exported/fmt/chrono.h
  3rdparty/exported/fmt/color.h
  3rdparty/exported/fmt/compile.h
  3rdparty/exported/fmt/core.h
  3rdparty/exported/fmt/format-inl.h
  3rdparty/exported/fmt/format.h
  3rdparty/exported/fmt/os.h
  3rdparty/exported/fmt/ostream.h
  3rdparty/exported/fmt/printf.h
  3rdparty/exported/fmt/ranges.h
  3rdparty/exported/fmt/std.h
  3rdparty/exported/fmt/xchar.h
  CHANGELOG.md
  cgmanifest.json
  include/ccf/crypto/san.h
  include/ccf/ds/unit_strings.h
  include/ccf/service/node_info.h
  include/ccf/service/node_info_network.h
  include/ccf/service/tables/proposals.h
  src/clients/perf/scenario_perf_client.cpp
  src/clients/perf/timing.h
  src/host/lfs_file_handler.h
  src/host/snapshots.h
  src/kv/kv_types.h
  src/node/acme_client.h
Labels: auto-backport, 4.x-todo

#5607 Update `llhttp` from `6.0.9` to `9.0.1`
  3rdparty/exported/llhttp/api.c
  3rdparty/exported/llhttp/llhttp.c
  3rdparty/exported/llhttp/llhttp.h
  CHANGELOG.md
  cgmanifest.json
  include/ccf/http_status.h
  src/endpoints/grpc/grpc_status.h
Labels: auto-backport, 4.x-todo

#5606 Update CLI11 from `2.2.0` to `2.3.2`
  3rdparty/internal/CLI11/App.hpp
  3rdparty/internal/CLI11/CLI11.hpp
  3rdparty/internal/CLI11/Config.hpp
  3rdparty/internal/CLI11/ConfigFwd.hpp
  3rdparty/internal/CLI11/Error.hpp
  3rdparty/internal/CLI11/Formatter.hpp
  3rdparty/internal/CLI11/FormatterFwd.hpp
  3rdparty/internal/CLI11/Macros.hpp
  3rdparty/internal/CLI11/Option.hpp
  3rdparty/internal/CLI11/Split.hpp
  3rdparty/internal/CLI11/StringTools.hpp
  3rdparty/internal/CLI11/Timer.hpp
  3rdparty/internal/CLI11/TypeTools.hpp
  3rdparty/internal/CLI11/Validators.hpp
  3rdparty/internal/CLI11/Version.hpp
  cgmanifest.json
Labels: auto-backport, 4.x-todo

#5611 [release/4.x] Cherry pick: Upgrade `nghttp` from `1.51.0` to `1.55.1` (#5604)
  .daily_canary
  3rdparty/exported/nghttp2/CMakeLists.txt
  3rdparty/exported/nghttp2/Makefile.am
  3rdparty/exported/nghttp2/Makefile.in
  3rdparty/exported/nghttp2/Makefile.msvc
  3rdparty/exported/nghttp2/includes/Makefile.in
  3rdparty/exported/nghttp2/includes/nghttp2/nghttp2ver.h
  3rdparty/exported/nghttp2/nghttp2_http.c
  3rdparty/exported/nghttp2/nghttp2_http.h
  3rdparty/exported/nghttp2/nghttp2_map.c
  3rdparty/exported/nghttp2/nghttp2_map.h
  3rdparty/exported/nghttp2/nghttp2_session.c
  3rdparty/exported/nghttp2/sfparse.c
  3rdparty/exported/nghttp2/sfparse.h
  CHANGELOG.md
  cgmanifest.json
  cmake/nghttp2.cmake
Labels: 4.x-backport

#5612 [release/4.x] Cherry pick: Update `QCBOR` from `1.1` to `1.2` (#5608)
  3rdparty/exported/QCBOR/CMakeLists.txt
  3rdparty/exported/QCBOR/Makefile
  3rdparty/exported/QCBOR/README.md
  3rdparty/exported/QCBOR/example.c
  3rdparty/exported/QCBOR/qcbor/UsefulBuf.h
  3rdparty/exported/QCBOR/qcbor/qcbor_common.h
  3rdparty/exported/QCBOR/qcbor/qcbor_decode.h
  3rdparty/exported/QCBOR/qcbor/qcbor_spiffy_decode.h
  3rdparty/exported/QCBOR/src/UsefulBuf.c
  3rdparty/exported/QCBOR/src/qcbor_decode.c
  3rdparty/exported/QCBOR/src/qcbor_encode.c
  3rdparty/exported/QCBOR/test/CMakeLists.txt
  3rdparty/exported/QCBOR/test/UsefulBuf_Tests.c
  3rdparty/exported/QCBOR/test/float_tests.c
  3rdparty/exported/QCBOR/test/not_well_formed_cbor.h
  3rdparty/exported/QCBOR/test/qcbor_decode_tests.c
  3rdparty/exported/QCBOR/test/qcbor_encode_tests.c
  3rdparty/exported/QCBOR/test/run_tests.c
  3rdparty/exported/QCBOR/ub-example.c
  CHANGELOG.md
  cgmanifest.json
Labels: 4.x-backport

#5620 SEV-SNP: Make UVM endorsements SVN an arbitrary string
  .snpcc_canary
  CHANGELOG.md
  doc/schemas/gov_openapi.json
  include/ccf/service/tables/uvm_endorsements.h
  samples/constitutions/default/actions.js
  src/node/quote.cpp
  src/node/rpc/member_frontend.h
  src/node/uvm_endorsements.h
  tests/code_update.py
Labels: auto-backport, 4.x-todo

#5616 Update SGX PSW from 2.18 to 2.20
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  docker/ccf_ci_built
  docker/sgx_deps_pin.sh
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 4.x-todo

#5623 [release/4.x] Cherry pick: Update `fmt` library from `9.1.0` to `10.1.1` (#5605)
  3rdparty/exported/fmt/args.h
  3rdparty/exported/fmt/chrono.h
  3rdparty/exported/fmt/color.h
  3rdparty/exported/fmt/compile.h
  3rdparty/exported/fmt/core.h
  3rdparty/exported/fmt/format-inl.h
  3rdparty/exported/fmt/format.h
  3rdparty/exported/fmt/os.h
  3rdparty/exported/fmt/ostream.h
  3rdparty/exported/fmt/printf.h
  3rdparty/exported/fmt/ranges.h
  3rdparty/exported/fmt/std.h
  3rdparty/exported/fmt/xchar.h
  CHANGELOG.md
  cgmanifest.json
  include/ccf/crypto/san.h
  include/ccf/ds/unit_strings.h
  include/ccf/service/node_info.h
  include/ccf/service/node_info_network.h
  include/ccf/service/tables/proposals.h
  src/clients/perf/scenario_perf_client.cpp
  src/clients/perf/timing.h
  src/host/lfs_file_handler.h
  src/host/snapshots.h
  src/kv/kv_types.h
  src/node/acme_client.h
Labels: 4.x-backport

#5627 [release/4.x] Cherry pick: SEV-SNP: Make UVM endorsements SVN an arbitrary string (#5620)
  CHANGELOG.md
  doc/schemas/gov_openapi.json
  include/ccf/service/tables/uvm_endorsements.h
  samples/constitutions/default/actions.js
  src/node/quote.cpp
  src/node/rpc/member_frontend.h
  src/node/uvm_endorsements.h
  tests/code_update.py
Labels: 4.x-backport

#5628 Add default `443` port to `verify_quote.sh`
  python/utils/verify_quote.sh
Labels: auto-backport, 4.x-todo

#5614 matchIndex lower bound for nextIndex
  tla/MCccfraft.cfg
  tla/MCccfraftWithReconfig.cfg
  tla/SIMccfraft.cfg
  tla/ccfraft.tla
Labels: tla

#5631 Syntactic change to show sender and receive in action labels of TLC counterexamples.
  tla/SIMccfraft.tla
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5624 [release/4.x] Cherry pick: Update CLI11 from `2.2.0` to `2.3.2` (#5606)
  3rdparty/internal/CLI11/App.hpp
  3rdparty/internal/CLI11/CLI11.hpp
  3rdparty/internal/CLI11/Config.hpp
  3rdparty/internal/CLI11/ConfigFwd.hpp
  3rdparty/internal/CLI11/Error.hpp
  3rdparty/internal/CLI11/Formatter.hpp
  3rdparty/internal/CLI11/FormatterFwd.hpp
  3rdparty/internal/CLI11/Macros.hpp
  3rdparty/internal/CLI11/Option.hpp
  3rdparty/internal/CLI11/Split.hpp
  3rdparty/internal/CLI11/StringTools.hpp
  3rdparty/internal/CLI11/Timer.hpp
  3rdparty/internal/CLI11/TypeTools.hpp
  3rdparty/internal/CLI11/Validators.hpp
  3rdparty/internal/CLI11/Version.hpp
  cgmanifest.json
Labels: 4.x-backport

#5619 Remove redirection usage APIs expected to be used through a load balancer
  .daily_canary
  doc/schemas/node_openapi.json
  src/host/main.cpp
  src/node/rpc/node_frontend.h
  tests/e2e_common_endpoints.py
Labels: auto-backport, 4.x-todo

#5633 Add two high-level liveness properties and a suitable fairness constraints.
  tla/ccfraft.tla
Labels: tla

#5630 matchIndex lower bound for nextIndex
  src/consensus/aft/raft.h
  tla/ccfraft.tla
Labels: consensus, tla

#5635 Restore use of `-lvi-cfg` variants of OE libs
  cmake/open_enclave.cmake
Labels: auto-backport, 4.x-todo

#5634 Support modeling different network guarantees.
  tla/Network.tla
  tla/Traceccfraft.cfg
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5637 [release/4.x] Cherry pick: OpenSSL3: remove use of deprecated functions (#5481)
  CHANGELOG.md
  CMakeLists.txt
  cmake/crypto.cmake
  cmake/open_enclave.cmake
  cmake/t_cose.cmake
  src/clients/tls_client.h
  src/crypto/key_wrap.cpp
  src/crypto/openssl/cose_verifier.cpp
  src/crypto/openssl/key_pair.cpp
  src/crypto/openssl/openssl_wrappers.h
  src/crypto/openssl/public_key.cpp
  src/crypto/openssl/public_key.h
  src/crypto/openssl/rsa_key_pair.cpp
  src/crypto/openssl/rsa_public_key.cpp
  src/crypto/openssl/rsa_public_key.h
  src/crypto/openssl/verifier.cpp
  src/crypto/test/crypto.cpp
  src/enclave/enclave.h
  src/enclave/tls_session.h
  src/node/snapshot_serdes.h
Labels: 4.x-backport

#5621 Use optimised OpenSSL SHA256 function for Merkle Tree hashing
  .daily_canary
  .threading_canary
  CMakeLists.txt
  src/node/history.h
  src/node/test/historical_queries.cpp
  src/node/test/merkle_bench.cpp
  src/node/test/merkle_test.cpp
  src/node/test/receipt.cpp
Labels: auto-backport, 4.x-todo

#5645 [{release/4.x}] Cherry pick: {Update SGX PSW from 2.18 to 2.20 (#5616)}
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  docker/ccf_ci_built
  docker/sgx_deps_pin.sh
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#5646 [release/4.x] Cherry pick: Restore use of `-lvi-cfg` variants of OE libs (#5635)
  cmake/open_enclave.cmake
Labels: 4.x-backport

#5638 [release/4.x] Cherry pick: Faster SHA256 OpenSSL hashing (#5548)
  .daily_canary
  .threading_canary
  src/clients/perf/scenario_perf_client.cpp
  src/crypto/openssl/hash.cpp
  src/crypto/openssl/hash.h
  src/crypto/test/bench.cpp
  src/crypto/test/crypto.cpp
  src/enclave/enclave.h
  src/host/test/ledger.cpp
  src/indexing/test/indexing.cpp
  src/kv/test/kv_contention.cpp
  src/kv/test/kv_test.cpp
  src/node/rpc/test/frontend_test.cpp
  src/node/rpc/test/node_frontend_test.cpp
  src/node/test/encryptor.cpp
  src/node/test/historical_queries.cpp
  src/node/test/history.cpp
  src/node/test/history_bench.cpp
  src/node/test/snapshot.cpp
  src/node/test/snapshotter.cpp
  tests/perf-system/submitter/submit.cpp
Labels: 4.x-backport

#5651 Move Alias to ccfraft.
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5650 Misc OpenSSL 3.x fixes
  .daily_canary
  CMakeLists.txt
  src/apps/tpcc/clients/tpcc_client.cpp
  src/apps/tpcc/tpcc.cmake
  src/indexing/test/indexing.cpp
Labels: auto-backport, 4.x-todo

#5657 Match next logline iff AE response comes from the same node.
  tla/Traceccfraft.tla
Labels: tla

#5654 [release/4.x] Cherry pick: Misc OpenSSL 3.x fixes (#5650)
  .daily_canary
  src/apps/tpcc/clients/tpcc_client.cpp
  src/apps/tpcc/tpcc.cmake
  src/indexing/test/indexing.cpp
Labels: 4.x-backport

#5656 Split a Virtual Tracing Build
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/ninja.yml
  .azure-pipelines-templates/test.yml
  .daily_canary
Labels: tla

#5649 Validate committable indices
  src/consensus/aft/raft.h
  tla/MCccfraft.cfg
  tla/MCccfraftWithReconfig.cfg
  tla/SIMccfraft.cfg
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5648 [release/4.x] Cherry pick: Remove our copy of attestation container now that it has moved repos (#5533)
  .attestation_container_canary
  .azure-pipelines-attestation-container.yml
  .azure-pipelines-templates/configure.yml
  .azure-pipelines-templates/deploy_attestation_container.yml
  .azure-pipelines-templates/test_attestation_container.yml
  .github/dependabot.yml
  .github/workflows/attestation_container_image.yml
  .gitignore
  CMakeLists.txt
  attestation-container/.dockerignore
  attestation-container/.gitignore
  attestation-container/CMakeLists.txt
  attestation-container/Dockerfile
  attestation-container/README.md
  attestation-container/attest/attestation.go
  attestation-container/attest/attestation_endorsement.go
  attestation-container/attest/attestation_endorsement_test.go
  attestation-container/attest/attestation_test.go
  attestation-container/attest/testdata/host_amd_certificate_env
  attestation-container/attestation-container.go
  attestation-container/attestation-container_test.go
  attestation-container/go.mod
  attestation-container/go.sum
  attestation-container/protobuf/attestation-container.pb.go
  attestation-container/protobuf/attestation-container.proto
  attestation-container/protobuf/attestation-container_grpc.pb.go
  attestation-container/uvm/uvm_endorsement.go
  attestation-container/uvm/uvm_endorsement_test.go
  scripts/azure_deployment/arm_aci.py
  scripts/ci-checks.sh
  tests/external_executor/executors/Dockerfile
  tests/external_executor/executors/app.py
  tests/external_executor/executors/ccf/executors/registration.py
  tests/external_executor/executors/utils/executor_container.py
Labels: 4.x-backport

#5658 Refactor IsRcvAppendEntriesRequest to eliminate conjunct that matches the *next* logline.
  tla/Traceccfraft.tla
Labels: tla

#5661 Refactor DropResponseWhenNotInState into arity-3 operator.
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5662 Bug: Why calculate nextIndex based on *old* state of log?!
  tla/ccfraft.tla
Labels: tla

#5643 Match fancy_election.2 by modeling rollbacks in become_follower().
  .azure-pipelines-templates/trace_validation.yml
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5665 Pass enclave path as CLI argument rather than in configuration
  .daily_canary
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  src/host/configuration.h
  src/host/main.cpp
  tests/config.jinja
  tests/e2e_operations.py
  tests/infra/remote.py
Labels: auto-backport, 4.x-todo

#5655 Replace Secret Sharing implementation
  .daily_canary
  CHANGELOG.md
  CMakeLists.txt
  cmake/crypto.cmake
  doc/governance/adding_member.rst
  doc/operations/recovery.rst
  include/ccf/crypto/hkdf.h
  include/ccf/crypto/sha256.h
  src/crypto/hash.cpp
  src/crypto/openssl/hash.cpp
  src/crypto/openssl/hash.h
  src/crypto/sharing.cpp
  src/crypto/sharing.h
  src/crypto/test/bench.cpp
  src/crypto/test/secret_sharing.cpp
  src/node/channels.h
  src/node/rpc/member_frontend.h
  src/node/share_manager.h
  tests/perf-system/submitter/CMakeLists.txt
Labels: auto-backport, 4.x-todo

#5673 Log and throw when oversized writer blows up
  src/ds/oversized.h
Labels: auto-backport, 4.x-todo

#5679 Refactor invariants to prevent evaluation error when they appear as conjuncts of the initial predicate.
  tla/ccfraft.tla
Labels: tla

#5681 Fix `lts_compatibility`: Bump version check for `--enclave-file` arg
  tests/infra/remote.py
Labels: auto-backport, 4.x-todo

#5680 Fix HTTP handling errors reporting
  src/enclave/rpc_sessions.h
  src/http/error_reporter.h
  src/http/http2_session.h
  src/http/http_session.h
  tests/infra/jwt_issuer.py
  tests/jwt_test.py
Labels: auto-backport, 4.x-todo

#5682 Do not assume UTC in CurlClient, but encourage it in the doc
  doc/governance/accept_recovery.rst
  doc/governance/adding_member.rst
  doc/governance/common_member_operations.rst
  doc/governance/hsm_keys.rst
  doc/governance/open_network.rst
  doc/governance/proposals.rst
  tests/governance_js.py
  tests/infra/clients.py
  tests/infra/member.py
Labels: auto-backport, 4.x-todo

#5683 [release/4.x] Cherry pick: Fix HTTP handling errors reporting (#5680)
  src/enclave/rpc_sessions.h
  src/http/error_reporter.h
  src/http/http2_session.h
  src/http/http_session.h
  tests/infra/jwt_issuer.py
  tests/jwt_test.py
Labels: 4.x-backport

#5688 Pin JS dependency to resolve `npm test` failure
  js/ccf-app/package.json
Labels: auto-backport, 4.x-todo

#5686 Add CLI argument for SNP context directory
  .snpcc_canary
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  doc/operations/platforms/snp.rst
  src/host/configuration.h
  src/host/main.cpp
  tests/config.jinja
  tests/infra/remote.py
Labels: auto-backport, 4.x-todo

#5689 [release/4.x] Cherry pick: Pin JS dependency to resolve &#x60;npm test&#x60; failure (#5688)
  js/ccf-app/package.json
Labels: 4.x-backport

#5693 Fix out of bounds copy in SNP attestation report req
  .snpcc_canary
  include/ccf/pal/attestation.h
Labels: auto-backport, 4.x-todo

#5692 Add basic backpressure mechanism if primary has too many in-flight transactions
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  include/ccf/endpoint_registry.h
  include/ccf/odata_error.h
  include/ccf/service/consensus_config.h
  src/consensus/aft/raft.h
  src/consensus/aft/test/test_common.h
  src/consensus/consensus_types.h
  src/kv/kv_types.h
  src/kv/test/stub_consensus.h
  src/node/rpc/frontend.h
  src/node/rpc/node_frontend.h
  tests/config.jinja
  tests/e2e_operations.py
  tests/infra/basicperf.py
  tests/infra/remote.py
  tests/requirements.txt
Labels: auto-backport, 4.x-todo
