Repository microsoft/CCF, pull requests merged in 2023-06, with the labels that each got.

#5310 Fix SNP CI pipeline
  .daily_canary
  .snpcc_canary
  tests/code_update.py
  tests/external_executor/external_executor.py
  tests/governance.py
Labels: auto-backport, 4.x-todo

#5323 Syntactic Refactoring of Traceccfraft.tla
  tla/Traceccfraft.tla
Labels: tla

#5329 Log values of committable_indices in TLA+ validation JSON logging
  src/consensus/aft/raft.h
Labels: tla

#5336 Update OpenSSL SHA digest API
  .daily_canary
  include/ccf/crypto/hash_provider.h
  src/crypto/hash.cpp
  src/crypto/openssl/hash.cpp
  src/crypto/openssl/hash.h
  src/crypto/test/crypto.cpp
Labels: auto-backport, 3.x-todo, 4.x-todo

#5349 LTS compatibility: no longer run 1.x and 2.x nodes
  .daily_canary
  tests/infra/github.py
  tests/lts_compatibility.py
  tests/testdata/eol_service/common/member0_cert.pem
  tests/testdata/eol_service/common/member0_enc_privk.pem
  tests/testdata/eol_service/common/member0_enc_pubk.pem
  tests/testdata/eol_service/common/member0_privk.pem
  tests/testdata/eol_service/common/member1_cert.pem
  tests/testdata/eol_service/common/member1_enc_privk.pem
  tests/testdata/eol_service/common/member1_enc_pubk.pem
  tests/testdata/eol_service/common/member1_privk.pem
  tests/testdata/eol_service/common/member2_cert.pem
  tests/testdata/eol_service/common/member2_enc_privk.pem
  tests/testdata/eol_service/common/member2_enc_pubk.pem
  tests/testdata/eol_service/common/member2_privk.pem
  tests/testdata/eol_service/common/service_cert.pem
  tests/testdata/eol_service/common/user0_cert.pem
  tests/testdata/eol_service/common/user0_privk.pem
  tests/testdata/eol_service/ledger/ledger_1-2.committed
  tests/testdata/eol_service/ledger/ledger_12-18.committed
  tests/testdata/eol_service/ledger/ledger_19-23.committed
  tests/testdata/eol_service/ledger/ledger_24-28.committed
  tests/testdata/eol_service/ledger/ledger_29-33.committed
  tests/testdata/eol_service/ledger/ledger_3-11.committed
  tests/testdata/eol_service/ledger/ledger_34-35.committed
  tests/testdata/eol_service/ledger/ledger_36-37.committed
  tests/testdata/eol_service/ledger/ledger_38-47.committed
  tests/testdata/eol_service/ledger/ledger_48-52.committed
  tests/testdata/eol_service/ledger/ledger_53-57.committed
  tests/testdata/eol_service/ledger/ledger_58-63.committed
  tests/testdata/eol_service/ledger/ledger_64
  tests/testdata/eol_service/snapshots/snapshot_63_64.committed
Labels: auto-backport, 3.x-todo, 4.x-todo

#5346 Remove `/opt/ccf` install from runtime images
  getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
Labels: auto-backport, 3.x-todo, 4.x-todo

#5348 Ensure e2e HTTP limit args are passed all the way through to the nodes
  tests/infra/e2e_args.py
  tests/infra/interfaces.py
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/remote.py
  tests/start_network.py
Labels: auto-backport, 3.x-todo, 4.x-todo

#5326 Do not decrement `match_idx` when processing NACKs
  .daily_canary
  src/consensus/aft/raft.h
  src/consensus/aft/raft_types.h
  src/consensus/aft/test/driver.cpp
  src/consensus/aft/test/driver.h
  tests/raft_scenarios/suffix_collision.2
  tests/raft_scenarios/suffix_collision.3
Labels: auto-backport, 3.x-todo, 4.x-todo

#5355 Validate all traces, and improve output somewhat
  .azure-pipelines-templates/trace_validation.yml
  tla/Traceccfraft.tla
Labels: tla

#5364 Documentation: Point from C++ crypto page to JS crypto API
  doc/build_apps/crypto.rst
Labels: auto-backport, 3.x-todo, 4.x-todo

#5356 Another attempt at ignoring RVRs and AERs when not in the right state
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5366 [release/4.x] Cherry pick: Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)
  tests/infra/e2e_args.py
  tests/infra/interfaces.py
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/remote.py
  tests/start_network.py
Labels: 4.x-backport

#5363 Add matching of match_idx and sent_idx to trace validation (Traceccfraft.tla).
  .azure-pipelines-templates/trace_validation.yml
  tla/Traceccfraft.tla
  tla/ccfraft.tla
Labels: tla

#5369 [release/3.x] Cherry pick: Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)
  tests/infra/e2e_args.py
  tests/infra/interfaces.py
  tests/infra/network.py
  tests/infra/node.py
  tests/infra/remote.py
  tests/start_network.py
Labels: 3.x-backport

#5373 Minor OpenSSL 3.x compatibility fixes
  src/crypto/test/crypto.cpp
Labels: auto-backport, 3.x-todo, 4.x-todo

#5370 Update error message for conflicting n2n published address
  doc/host_config_schema/cchost_config.json
  src/node/rpc/node_frontend.h
  src/node/rpc/test/node_frontend_test.cpp
Labels: auto-backport, 3.x-todo, 4.x-todo

#5374 Enable multi election trace validation
  .azure-pipelines-templates/trace_validation.yml
Labels: tla

#5351 Improve error reporting in trace validation spec
  .azure-pipelines-templates/trace_validation.yml
  tla/Traceccfraft.cfg
  tla/Traceccfraft.tla
Labels: tla

#5379 Add config timeout option
  CHANGELOG.md
  src/host/main.cpp
  tests/e2e_operations.py
Labels: auto-backport, 4.x-todo

#5395 Boilerplate to validate the current TLA+ trace against an older trace.
  tla/Traceccfraft.cfg
  tla/Traceccfraft.tla
Labels: tla

#5391 Toward trace validating raft_scenarios/election_while_reconfiguration
  tla/Traceccfraft.cfg
  tla/Traceccfraft.tla
Labels: tla
