Repository microsoft/CCF, pull requests merged in 2023-08, with the labels that each got.

#5520 Ruff lint update: Use `isinstance`
  tests/infra/piccolo/generator.py
Labels: auto-backport, 4.x-todo

#5529 Install vegeta and pebble and run corresponding tests in Daily
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/install_extended_testing_tools.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/stress-matrix.yml
  .daily_canary
  .multi-thread.yml
  CMakeLists.txt
  getting_started/setup_vm/ccf-dev.yml
  getting_started/setup_vm/ccf-extended-testing.yml
Labels: auto-backport, 3.x-todo, 4.x-todo

#5530 [release/4.x] Cherry pick: Install vegeta and pebble and run corresponding tests in Daily (#5529)
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/install_extended_testing_tools.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/stress-matrix.yml
  .multi-thread.yml
  CMakeLists.txt
  getting_started/setup_vm/ccf-dev.yml
  getting_started/setup_vm/ccf-extended-testing.yml
Labels: 4.x-backport

#5532 Update CI jobs to 10-08-2023 base
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 3.x-todo, 4.x-todo

#5531 [release/3.x] Cherry pick: Install vegeta and pebble and run corresponding tests in Daily (#5529)
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/install_extended_testing_tools.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/stress-matrix.yml
  .daily_canary
  .multi-thread.yml
  CMakeLists.txt
  getting_started/setup_vm/ccf-dev.yml
  getting_started/setup_vm/ccf-extended-testing.yml
Labels: 3.x-backport

#5534 [release/4.x] Cherry pick: Remove GHA SNP CI container builder (#5471)
  .azure-pipelines-templates/azure_cli.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines-templates/install_ssh_key.yml
  .azure_pipelines_snp.yml
  .github/workflows/build-ci-container.yml
  docker/ccf_ci_built
Labels: 4.x-backport

#5536 [release/4.x] Cherry pick: Update CI jobs to 10-08-2023 base (#5532)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#5537 [release/3.x] Cherry pick: Update CI jobs to 10-08-2023 base (#5532)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
Labels: 3.x-backport

#5538 Update CI image to 11-08-2023
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 3.x-todo, 4.x-todo

#5547 [release/3.x] Cherry pick: Update CI image from 11-08 to 14-08 (#5544)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
Labels: 3.x-backport

#5552 Fix SNP CI authentication
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines-templates/test_on_remote.yml
  .azure_pipelines_snp.yml
  scripts/azure_deployment/arm_aci.py
  scripts/azure_deployment/arm_template.py
  tests/code_update.py
  tests/infra/e2e_args.py
Labels: auto-backport, 4.x-todo

#5559 [release/3.x] Cherry pick: Switch to a backup pool (#5512)
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/matrix.yml
  .azure-pipelines-templates/stress-matrix.yml
Labels: 3.x-backport

#5554 [release/4.x] Cherry pick: Remove graphviz from llvm task (#5551)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  getting_started/setup_vm/roles/autoremove/install.yml
  getting_started/setup_vm/roles/ccf_build/vars/clang11.yml
  getting_started/setup_vm/roles/ccf_build/vars/clang15.yml
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#5561 [release/3.x] Cherry pick: Remove graphviz from llvm task (#5551)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  getting_started/setup_vm/roles/ccf_build/vars/clang11.yml
  getting_started/setup_vm/roles/ccf_build/vars/clang15.yml
Labels: 3.x-backport

#5563 TLC will report a bogus violation of the property TraceMatched if TLC…
  tla/Traceccfraft.tla
Labels: documentation, tla

#5566 Do not compare types, use `isinstance()`
  tests/election.py
Labels: auto-backport, 3.x-todo, 4.x-todo

#5565 [release/4.x] Cherry pick: Fix SNP CI authentication (#5552)
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines-templates/test_on_remote.yml
  .azure_pipelines_snp.yml
  scripts/azure_deployment/arm_aci.py
  scripts/azure_deployment/arm_template.py
  tests/code_update.py
  tests/infra/e2e_args.py
Labels: 4.x-backport

#5572 Update merklecpp from `1.0.1` to `1.1.0`
  3rdparty/exported/merklecpp/merklecpp.h
  cgmanifest.json
Labels: auto-backport, 4.x-todo

#5580 Install testing tools for release jobs
  .azure-pipelines-templates/matrix.yml
Labels: auto-backport, 4.x-todo

#5577 Fix SNP reconfiguration test error
  include/ccf/pal/attestation_sev_snp_endorsements.h
  scripts/azure_deployment/arm_template.py
  src/node/quote_endorsements_client.h
Labels: auto-backport, 4.x-todo

#5584 [release/4.x] Cherry pick: Fix schema test in SNP (#5581)
  .snpcc_canary
  tests/e2e_operations.py
Labels: 4.x-backport

#5587 [release/4.x] Cherry pick: Add app and gov read endpoints (#5574)
  CHANGELOG.md
  doc/schemas/node_openapi.json
  src/node/node_state.h
  src/node/rpc/node_frontend.h
  src/node/rpc/node_interface.h
  src/node/rpc/node_operation.h
  src/node/rpc/node_operation_interface.h
  src/node/rpc/test/node_stub.h
  tests/e2e_common_endpoints.py
  tests/e2e_operations.py
  tests/reconfiguration.py
  tests/recovery.py
Labels: 4.x-backport

#5592 Find a *shorter* counter-example.
  tla/SIMccfraft.tla
Labels: tla
