Repository microsoft/CCF, pull requests merged in 2023-01, with the labels that each got.

#4791 Decompose `Receive` action to see sub-action names in counterexamples.
  tla/ccfraft.tla
Labels: tla

#4824 Terminate raft_scenario input with four or more equal sign characters…
  src/consensus/aft/test/driver.cpp
Labels: enhancement, testing

#4829 Use p1363 encoding for sign() JS API with ECDSA
  CHANGELOG.md
  include/ccf/crypto/ecdsa.h
  js/ccf-app/test/polyfill.test.ts
  src/crypto/ecdsa.cpp
  src/crypto/openssl/openssl_wrappers.h
  src/js/crypto.cpp
  tests/infra/crypto.py
  tests/js-modules/modules.py
Labels: auto-backport, 3.x-todo

#4838 Add `enableUntrustedDateTime` to JS API
  3rdparty/exported/quickjs/quickjs-time.h
  3rdparty/exported/quickjs/quickjs.c
  CHANGELOG.md
  doc/build_apps/js_app_bundle.rst
  js/ccf-app/src/global.ts
  js/ccf-app/src/polyfill.ts
  src/js/wrap.cpp
  src/js/wrap.h
  tests/js-api/app.json
  tests/js-api/src/endpoints.js
  tests/js-custom-authorization/custom_authorization.py
Labels: auto-backport, 3.x-todo

#4842 Unpin mistune
  doc/requirements.txt
Labels: auto-backport, 3.x-todo

#4841 [release/3.x] Cherry pick: Add `enableUntrustedDateTime` to JS API (#4838)
  3rdparty/exported/quickjs/quickjs-time.h
  3rdparty/exported/quickjs/quickjs.c
  CHANGELOG.md
  doc/build_apps/js_app_bundle.rst
  js/ccf-app/src/global.ts
  js/ccf-app/src/polyfill.ts
  src/js/wrap.cpp
  src/js/wrap.h
  tests/js-api/app.json
  tests/js-api/src/endpoints.js
  tests/js-custom-authorization/custom_authorization.py
Labels: 3.x-backport

#4873 Polish instructions to run simulation.
  tla/SIMccfraft.tla
Labels: tla

#4870 Update paths and package names
  doc/build_apps/install_bin.rst
  doc/build_apps/run_app.rst
Labels: auto-backport, 3.x-todo

#4876 Add JWK to PEM converters
  .daily_canary
  CHANGELOG.md
  include/ccf/crypto/eddsa_key_pair.h
  include/ccf/crypto/jwk.h
  include/ccf/crypto/key_pair.h
  include/ccf/crypto/rsa_key_pair.h
  include/ccf/crypto/rsa_public_key.h
  js/ccf-app/src/crypto.ts
  js/ccf-app/src/global.ts
  js/ccf-app/src/polyfill.ts
  js/ccf-app/test/polyfill.test.ts
  src/crypto/eddsa_key_pair.cpp
  src/crypto/key_pair.cpp
  src/crypto/openssl/eddsa_key_pair.cpp
  src/crypto/openssl/eddsa_key_pair.h
  src/crypto/openssl/eddsa_public_key.cpp
  src/crypto/openssl/eddsa_public_key.h
  src/crypto/openssl/key_pair.cpp
  src/crypto/openssl/key_pair.h
  src/crypto/openssl/openssl_wrappers.h
  src/crypto/openssl/public_key.cpp
  src/crypto/openssl/public_key.h
  src/crypto/openssl/rsa_key_pair.cpp
  src/crypto/openssl/rsa_key_pair.h
  src/crypto/openssl/rsa_public_key.cpp
  src/crypto/openssl/rsa_public_key.h
  src/crypto/rsa_key_pair.cpp
  src/crypto/test/crypto.cpp
  src/js/crypto.cpp
  src/js/wrap.cpp
  tests/js-modules/modules.py
  tests/npm-app/app.json
  tests/npm-app/src/endpoints/crypto.ts
Labels: auto-backport, 3.x-todo

#4823 Add ccf gov msg created at
  CHANGELOG.md
  doc/audit/builtin_maps.rst
  doc/governance/accept_recovery.rst
  doc/governance/adding_member.rst
  doc/governance/common_member_operations.rst
  doc/governance/hsm_keys.rst
  doc/governance/open_network.rst
  doc/governance/proposals.rst
  doc/host_config_schema/cchost_config.json
  doc/schemas/gov_openapi.json
  doc/schemas/node_openapi.json
  doc/use_apps/issue_commands.rst
  include/ccf/endpoints/authentication/cose_auth.h
  include/ccf/odata_error.h
  include/ccf/service/service_config.h
  include/ccf/service/tables/gov.h
  python/ccf/cose.py
  samples/constitutions/default/actions.js
  samples/constitutions/test/resolve.js
  samples/constitutions/test/test_actions.js
  src/endpoints/authentication/cose_auth.cpp
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
  src/service/network_tables.h
  src/service/tables/config.h
  src/service/tables/governance_history.h
  tests/governance.py
  tests/governance_js.py
  tests/infra/clients.py
  tests/infra/network.py
  tests/recovery.py
Labels: auto-backport, 3.x-todo

#4882 [release/3.x] Cherry pick: Add ccf gov msg created at (#4823)
  CHANGELOG.md
  doc/audit/builtin_maps.rst
  doc/governance/accept_recovery.rst
  doc/governance/adding_member.rst
  doc/governance/common_member_operations.rst
  doc/governance/hsm_keys.rst
  doc/governance/open_network.rst
  doc/governance/proposals.rst
  doc/host_config_schema/cchost_config.json
  doc/schemas/gov_openapi.json
  doc/schemas/node_openapi.json
  doc/use_apps/issue_commands.rst
  include/ccf/endpoints/authentication/cose_auth.h
  include/ccf/odata_error.h
  include/ccf/service/service_config.h
  include/ccf/service/tables/gov.h
  python/ccf/cose.py
  samples/constitutions/default/actions.js
  samples/constitutions/test/resolve.js
  samples/constitutions/test/test_actions.js
  src/endpoints/authentication/cose_auth.cpp
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
  src/service/network_tables.h
  src/service/tables/config.h
  src/service/tables/governance_history.h
  tests/governance.py
  tests/governance_js.py
  tests/infra/clients.py
  tests/infra/network.py
  tests/recovery.py
Labels: 3.x-backport

#4890 `cchost --version` reports target platform
  src/host/main.cpp
Labels: auto-backport, 3.x-todo

#4887 Resolve occasional replay in governance test
  tests/governance.py
  tests/governance_js.py
Labels: auto-backport, 3.x-todo

#4893 Fix set_service_config action
  .daily_canary
  samples/constitutions/default/actions.js
Labels: auto-backport, 3.x-todo

#4868 Nodes may not rejoin a configuration.
  tla/SIMccfraft.tla
  tla/ccfraft.tla
Labels: tla

#4859 Fixing QuorumLogInv in TLA+ spec
  tla/ccfraft.tla
Labels: tla

#4867 Pending nodes must not be part of a configuration.
  tla/MCccfraft.cfg
  tla/SIMccfraft.cfg
  tla/ccfraft.tla
Labels: tla
