Repository microsoft/CCF, pull requests merged in 2023-02, with the labels that each got.

#4949 Allow applications to add .well-known endpoints.
  include/ccf/actors.h
  src/enclave/enclave.h
  src/http/http_rpc_context.h
  src/node/acme_challenge_frontend.h
  src/node/node_state.h
Labels: auto-backport, 3.x-todo

#4928 A pending node that becomes part of any configuration immediately transitions to Follower state.
  tla/MCccfraft.cfg
  tla/SIMccfraft.cfg
  tla/ccfraft.tla
Labels: enhancement, tla

#4976 Historical queries: Re-request seqnos if host fails to respond
  .daily_canary
  CHANGELOG.md
  cmake/version.cmake
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
Labels: 2.x-todo, auto-backport, 3.x-todo

#4982 [release/2.x] Cherry pick: Historical queries: Re-request seqnos if host fails to respond (#4976)
  CHANGELOG.md
  cmake/version.cmake
  scripts/ci-checks.sh
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
Labels: 2.x-backport

#4964 Improve test coverage for historical range queries
  .azure-pipelines-templates/daily-matrix.yml
  .daily_canary
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  tests/e2e_logging.py
  tests/e2e_operations.py
  tests/historical_query_perf.py
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/lts_compatibility.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#4991 [release/3.x] Cherry pick: Improve test coverage for historical range queries (#4964)
  .azure-pipelines-templates/daily-matrix.yml
  .daily_canary
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  tests/e2e_logging.py
  tests/e2e_operations.py
  tests/historical_query_perf.py
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/lts_compatibility.py
Labels: 3.x-backport

#4983 [release/3.x] Cherry pick: Historical queries: Re-request seqnos if host fails to respond (#4976)
  CHANGELOG.md
  cmake/version.cmake
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
Labels: 3.x-backport

#4990 [release/2.x] Cherry pick: Improve test coverage for historical range queries (#4964)
  .azure-pipelines-templates/daily-matrix.yml
  .daily_canary
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  tests/e2e_logging.py
  tests/e2e_operations.py
  tests/historical_query_perf.py
  tests/infra/logging_app.py
  tests/infra/network.py
  tests/lts_compatibility.py
Labels: 2.x-backport

#5004 Upgrade to Open Enclave 0.18.5
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/build-ci-container.yml
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  getting_started/setup_vm/roles/openenclave/vars/common.yml
  scripts/azure_deployment/arm_aci.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#5008 [release/2.x] Cherry pick: Upgrade to Open Enclave 0.18.5 (#5004)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines-templates/cmake.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  getting_started/setup_vm/roles/openenclave/vars/common.yml
Labels: 2.x-backport

#5010 [release/3.x] Cherry pick: Upgrade to Open Enclave 0.18.5 (#5004)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-quictls.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  getting_started/setup_vm/roles/openenclave/vars/common.yml
Labels: 3.x-backport

#5014 Update t_cose from v1.1 to v1.1.1
  3rdparty/exported/t_cose/CONTRIBUTING.md
  3rdparty/exported/t_cose/inc/t_cose/t_cose_sign1_verify.h
  3rdparty/exported/t_cose/src/t_cose_sign1_verify.c
  3rdparty/exported/t_cose/test/t_cose_test.c
  CHANGELOG.md
  cgmanifest.json
Labels: auto-backport, 3.x-todo

#5019 Improve error messages in COSE Sign Auth policies
  include/ccf/endpoints/authentication/cose_auth.h
  src/endpoints/authentication/cose_auth.cpp
  src/node/rpc/member_frontend.h
  tests/governance.py
  tests/governance_js.py
  tests/infra/clients.py
Labels: auto-backport, 3.x-todo

#5023 [release/3.x] Cherry pick: Improve error messages in COSE Sign Auth policies (#5019)
  include/ccf/endpoints/authentication/cose_auth.h
  src/endpoints/authentication/cose_auth.cpp
  src/node/rpc/member_frontend.h
  tests/governance.py
  tests/governance_js.py
  tests/infra/clients.py
Labels: 3.x-backport

#5026 Historical queries: Handle large requests being truncated by the host
  src/host/ledger.h
  src/host/node_connections.h
  src/host/test/ledger.cpp
  src/indexing/test/indexing.cpp
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
  tests/e2e_logging.py
  tests/infra/logging_app.py
Labels: 2.x-todo, auto-backport, 3.x-todo

#5027 Efficient jwt refresh
  src/node/rpc/jwt_management.h
  tests/infra/jwt_issuer.py
  tests/js-modules/modules.py
  tests/jwt_test.py
Labels: auto-backport, 3.x-todo

#5052 [release/3.x] Cherry pick: Update cryptography requirement from ==38.* to ==39.* in /python (#4792)
  python/requirements.txt
Labels: 3.x-backport

#5053 [release/2.x] Cherry pick: Update cryptography requirement from ==38.* to ==39.* in /python (#4792)
  python/requirements.txt
Labels: 2.x-backport

#5058 Historical queries: Do not fetch entries until an early-enough secret has been fetched
  .daily_canary
  src/node/historical_queries.h
  tests/suite/test_suite.py
Labels: 2.x-todo, 3.x-todo

#5034 [release/2.x] Cherry pick: Historical queries fixes (#5026, #5040, #5058)
  CHANGELOG.md
  src/host/ledger.h
  src/host/node_connections.h
  src/host/test/ledger.cpp
  src/indexing/test/indexing.cpp
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
  tests/e2e_logging.py
  tests/infra/logging_app.py
Labels: 2.x-backport

#5033 [release/3.x] Cherry pick: Historical queries fixes (#5026, #5040, #5058)
  CHANGELOG.md
  src/host/ledger.h
  src/host/node_connections.h
  src/host/test/ledger.cpp
  src/indexing/test/indexing.cpp
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
  tests/e2e_logging.py
  tests/infra/logging_app.py
Labels: 3.x-backport

#5056 Add support for host process stdio.
  .daily_canary
  CHANGELOG.md
  CMakeLists.txt
  include/ccf/node/host_processes_interface.h
  src/enclave/interface.h
  src/host/process_launcher.h
  src/host/proxy.h
  src/js/wrap.cpp
  src/node/node_state.h
  src/node/rpc/host_processes.h
  src/node/rpc/node_interface.h
  src/node/rpc/test/node_stub.h
  tests/js-launch-host-process/host_process.py
  tests/js-launch-host-process/host_process.sh
  tests/js-launch-host-process/src/host_process.js
Labels: auto-backport, 3.x-todo
