Repository microsoft/CCF, pull requests merged in 2023-07, with the labels that each got.

#5408 Fix unsafe inline assembly usage
  include/ccf/crypto/entropy.h
Labels: auto-backport, 4.x-todo

#5375 Permit Trace+Debug logging in all non-SGX builds
  CHANGELOG.md
  CMakeLists.txt
  cmake/version.cmake
  doc/build_apps/logging.rst
  doc/contribute/build_ccf.rst
  doc/host_config_schema/cchost_config.json
  edl/ccf.edl
  include/ccf/ds/logger.h
  include/ccf/ds/logger_level.h
  scripts/scan-build.sh
  src/common/configuration.h
  src/common/enclave_interface_types.h
  src/consensus/aft/test/driver.cpp
  src/consensus/aft/test/main.cpp
  src/ds/test/logger_bench.cpp
  src/ds/test/logger_json_test.cpp
  src/enclave/interface.h
  src/enclave/main.cpp
  src/enclave/virtual_enclave.h
  src/host/configuration.h
  src/host/enclave.h
  src/host/main.cpp
  src/http/test/http_test.cpp
  src/kv/test/kv_bench.cpp
  src/kv/test/kv_contention.cpp
  src/node/rpc/gov_logging.h
  src/node/test/history_bench.cpp
  tests/infra/e2e_args.py
  tests/infra/network.py
  tests/infra/remote.py
Labels: auto-backport, 4.x-todo

#5426 Fix `logger_json_test`
  src/ds/test/logger_json_test.cpp
Labels: auto-backport, 4.x-todo

#5433 Fix `channels_test`
  .daily_canary
  include/ccf/ds/logger.h
  src/node/test/channels.cpp
Labels: auto-backport, 4.x-todo

#5418 Fix historical queries issue - sequence of operations could result in permanently missing receipts
  .daily_canary
  src/node/historical_queries.h
  src/node/test/historical_queries.cpp
Labels: auto-backport, 4.x-todo

#5443 Channels connections fix - clear shared secret when peer key changes
  .daily_canary
  src/crypto/key_exchange.h
  src/node/test/channels.cpp
Labels: auto-backport, 4.x-todo

#5413 Store deadlock fix
  .threading_canary
  src/kv/apply_changes.h
  src/kv/committable_tx.h
  src/kv/kv_types.h
  src/kv/store.h
  src/kv/test/stub_consensus.h
  src/node/history.h
  src/node/test/historical_queries.cpp
  src/node/test/history.cpp
  src/node/test/snapshot.cpp
  src/node/test/snapshotter.cpp
Labels: auto-backport, 4.x-todo

#5449 Remove shadowing instances from the code
  cmake/preproject.cmake
  src/apps/tpcc/app/tpcc_setup.h
  src/ds/state_machine.h
  src/host/ledger.h
  src/host/lfs_file_handler.h
  src/host/main.cpp
  src/host/tcp.h
  src/host/udp.h
  src/indexing/strategies/seqnos_by_key_bucketed.cpp
  src/kv/store.h
  src/kv/untyped_map.h
  src/node/acme_client.h
  src/node/historical_queries.h
  src/node/history.h
  src/node/node_state.h
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
  src/node/share_manager.h
Labels: auto-backport, 4.x-todo

#5451 Add `getVersionOfPreviousWrite` to TypeScript `TypedKvMap`
  CHANGELOG.md
  js/ccf-app/src/kv.ts
  tests/js-modules/modules.py
  tests/npm-app/app.json
  tests/npm-app/src/endpoints/log.ts
Labels: auto-backport, 4.x-todo

#5454 [release/4.x] Cherry pick: Remove shadowing instances from the code (#5449)
  cmake/preproject.cmake
  src/apps/tpcc/app/tpcc_setup.h
  src/ds/state_machine.h
  src/host/ledger.h
  src/host/lfs_file_handler.h
  src/host/main.cpp
  src/host/tcp.h
  src/host/udp.h
  src/indexing/strategies/seqnos_by_key_bucketed.cpp
  src/kv/store.h
  src/kv/untyped_map.h
  src/node/acme_client.h
  src/node/historical_queries.h
  src/node/history.h
  src/node/node_state.h
  src/node/rpc/member_frontend.h
  src/node/rpc/node_frontend.h
  src/node/share_manager.h
Labels: 4.x-backport

#5453 Include intermediate certs in TLS handshake
  .daily_canary
  CHANGELOG.md
  src/tls/cert.h
  tests/acme_endorsement.py
Labels: auto-backport, 4.x-todo

#5457 [release/4.x] Cherry pick: Include intermediate certs in TLS handshake (#5453)
  CHANGELOG.md
  src/tls/cert.h
  tests/acme_endorsement.py
Labels: 4.x-backport

#5461 Fix `lts_compatibility` in SGX Debug - don't pass unsafe `--enclave-log-level`
  tests/infra/remote.py
Labels: auto-backport, 4.x-todo

#5460 Update to Open Enclave 0.19.3
  .azure-pipelines-gh-pages.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/build-ci-container.yml
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  getting_started/setup_vm/roles/openenclave/vars/common.yml
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 3.x-todo, 4.x-todo

#5466 [release/4.x] Cherry pick: Update to Open Enclave 0.19.3 (#5460)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/build-ci-container.yml
  .github/workflows/ci-checks.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  getting_started/setup_vm/roles/openenclave/vars/common.yml
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#5464 Fix SNP `code_update_test` - `ccf.digest` is now `ccf.crypto.digest`
  samples/constitutions/default/actions.js
Labels: auto-backport, 4.x-todo

#5468 [release/4.x] Cherry pick: Fix SNP `code_update_test` - `ccf.digest` is now `ccf.crypto.digest` (#5464)
  samples/constitutions/default/actions.js
Labels: 4.x-backport

#5465 Expose COSE identity content in JS/TS apps
  CHANGELOG.md
  js/ccf-app/src/endpoints.ts
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  src/apps/js_generic/js_generic_base.cpp
  tests/e2e_logging.py
  tests/js-modules/modules.py
  tests/npm-app/src/endpoints/auth.ts
  tests/npm-app/src/endpoints/rpc.ts
Labels: auto-backport, 4.x-todo

#5482 Fix bug in TLS context - allow incoming write buffer to be relocated
  src/enclave/tls_session.h
  src/tls/context.h
Labels: auto-backport, 4.x-todo
