Repository microsoft/CCF, pull requests merged in 2023-03, with the labels that each got.

#5072 Add support for host process stdio. (#5056)
  .daily_canary
  CHANGELOG.md
  CMakeLists.txt
  include/ccf/node/host_processes_interface.h
  src/enclave/interface.h
  src/host/process_launcher.h
  src/host/proxy.h
  src/js/wrap.cpp
  src/node/node_state.h
  src/node/rpc/host_processes.h
  src/node/rpc/node_interface.h
  src/node/rpc/test/node_stub.h
  tests/js-launch-host-process/host_process.py
  tests/js-launch-host-process/host_process.sh
  tests/js-launch-host-process/src/host_process.js
Labels: 3.x-backport

#5097 [release/3.x] Cherry pick: Avoid rewriting node info when `retired_committed` is already set (#5094)
  CHANGELOG.md
  src/node/rpc/node_frontend.h
Labels: 3.x-backport

#5096 [release/2.x] Cherry pick: Avoid rewriting node info when `retired_committed` is already set (#5094)
  CHANGELOG.md
  src/node/rpc/node_frontend.h
Labels: 2.x-backport

#5128 Remove unnecessary condition
  tla/ccfraft.tla
Labels: tla
