Repository microsoft/CCF, pull requests merged in 2024-08, with the labels that each got.

#6418 Fix flakiness for hist range test
  tests/e2e_logging.py
Labels: auto-backport, 5.x-todo

#6415 Replace RSASSA-PKCS1-v1_5 with RSA-PSS in crypto API
  CHANGELOG.md
  include/ccf/crypto/rsa_key_pair.h
  include/ccf/crypto/rsa_public_key.h
  js/ccf-app/src/global.ts
  js/ccf-app/src/polyfill.ts
  js/ccf-app/test/polyfill.test.ts
  src/crypto/openssl/rsa_key_pair.cpp
  src/crypto/openssl/rsa_key_pair.h
  src/crypto/openssl/rsa_public_key.cpp
  src/crypto/openssl/rsa_public_key.h
  src/crypto/test/crypto.cpp
  src/js/extensions/ccf/crypto.cpp
  tests/infra/crypto.py
  tests/npm_tests.py
Labels: auto-backport, 5.x-todo, 5.x-backport

#6431 Change raw issuer to digest before passing to x509
  tests/infra/crypto.py
  tests/js-custom-authorization/custom_authorization.py
Labels: auto-backport, 5.x-todo

#6432 Return schema correctly in gov/service/javascript-app endpoint
  CHANGELOG.md
  src/node/gov/handlers/service_state.h
Labels: auto-backport, 5.x-todo

#6435 Improve JWT auth error msg
  CHANGELOG.md
  src/endpoints/authentication/jwt_auth.cpp
  tests/js-custom-authorization/custom_authorization.py
Labels: auto-backport, 5.x-todo

#6440 Address issue with embedded certificates in JWT x5c
  CHANGELOG.md
  src/crypto/openssl/openssl_wrappers.h
  src/crypto/openssl/verifier.cpp
  src/crypto/pem.cpp
  src/crypto/test/crypto.cpp
  src/crypto/test/pem.cpp
Labels: auto-backport, 5.x-todo

#6454 Fixup verify quote script for load balancer
  python/utils/verify_quote.sh
Labels: auto-backport, 5.x-todo

#6451 Ensure raft traces are always uploaded as workflow artifacts.
  .github/workflows/tlaplus.yml
  tests/raft_scenarios_runner.py
Labels: enhancement, tla, github_actions
