Repository microsoft/CCF, pull requests merged in 2024-06, with the labels that each got.

#6229 Typed model values in consensus spec
  tla/consensus/MCccfraft.cfg
  tla/consensus/MCccfraftAtomicReconfig.cfg
  tla/consensus/MCccfraftWithReconfig.cfg
  tla/consensus/SIMCoverageccfraft.cfg
  tla/consensus/SIMccfraft.cfg
  tla/consensus/Traceccfraft.cfg
Labels: tla

#6262 Update from Open Enclave 0.19.4 to 0.19.6
  getting_started/setup_vm/roles/openenclave/vars/common.yml
Labels: auto-backport, 4.x-todo

#6264 [release/4.x] Cherry pick: Update from Open Enclave 0.19.4 to 0.19.6 (#6262)
  getting_started/setup_vm/roles/openenclave/vars/common.yml
Labels: 4.x-backport

#6263 Update to use latest CI image containing Open Enclave 0.19.6
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-model-checking.yml
  .azure-pipelines-release.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/bencher.yml
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 4.x-todo

#6272 [release/4.x] Cherry pick: Update to use latest CI image containing Open Enclave 0.19.6 (#6263)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#6185 New definition of TxID ordered speculative linearizability
  tla/consistency/ExternalHistoryInvars.tla
  tla/consistency/MCMultiNode.cfg
  tla/consistency/MCMultiNodeReads.cfg
Labels: tla

#6293 Upgrade base to open enclave 0.19.7
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-model-checking.yml
  .azure-pipelines-release.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/bencher.yml
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  getting_started/setup_vm/roles/openenclave/vars/common.yml
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 4.x-todo

#6294 [release/4.x] Cherry pick: Upgrade base to open enclave 0.19.7 (#6293)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  CHANGELOG.md
  cmake/cpack_settings.cmake
  cmake/open_enclave.cmake
  docker/ccf_ci_built
  getting_started/setup_vm/roles/openenclave/vars/common.yml
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport
