Repository microsoft/CCF, pull requests merged in 2024-04, with the labels that each got.

#6105 Update CI image from 2024-04-03 to 2024-03-15
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-model-checking.yml
  .azure-pipelines-release.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: auto-backport, 4.x-todo

#6106 [release/4.x] Cherry-pick: Update CI image from 2024-04-03 to 2024-03-15 (#6105)
  .azure-pipelines-gh-pages.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines.yml
  .azure_pipelines_snp.yml
  .daily.yml
  .devcontainer/devcontainer.json
  .github/workflows/ci-checks.yml
  .github/workflows/tlaplus.yml
  .multi-thread.yml
  .stress.yml
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
Labels: 4.x-backport

#6116 Basic consistency TV app and client
  CMakeLists.txt
  samples/apps/basic_tv/js/app.json
  samples/apps/basic_tv/js/src/basic.js
  tests/consistency_trace_validation.py
  tests/tvc.py
Labels: tla

#6129 Adding signature txn to consistency spec
  tla/consistency/MultiNode.tla
  tla/consistency/SingleNode.tla
  tla/consistency/SingleNodeReads.tla
Labels: tla

#6124 Consistency Spec Trace Validation
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/trace_validation.yml
  tests/consistency_trace_validation.py
  tests/tvc.py
  tla/consistency/TraceMultiNodeReads.cfg
  tla/consistency/TraceMultiNodeReads.tla
Labels: tla

#6131 Correct `builtin_maps` description of endpoints key
  doc/audit/builtin_maps.rst
Labels: documentation

#6154 Fix off by one in consistency tv
  .azure-pipelines-templates/trace_validation.yml
  tla/consistency/TraceMultiNodeReads.cfg
  tla/consistency/TraceMultiNodeReads.tla
Labels: tla
