Repository microsoft/CCF, pull requests merged in 2024-11, with the labels that each got.

#6609 Fix accessing invalid iterator in historical state
  src/node/historical_queries.h
Labels: auto-backport, 5.x-todo, run-long-test

#6613 OpenSSL 3.3: proper public key loading for EC keys
  src/crypto/openssl/public_key.cpp
Labels: auto-backport, 5.x-todo, run-long-test

#6608 Any cert authn policy
  CHANGELOG.md
  doc/build_apps/api.rst
  doc/build_apps/js_app_bundle.rst
  include/ccf/common_auth_policies.h
  include/ccf/endpoint.h
  include/ccf/endpoints/authentication/cert_auth.h
  include/ccf/endpoints/authentication/js.h
  js/ccf-app/src/endpoints.ts
  python/pyproject.toml
  samples/apps/logging/js/app.json
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  src/endpoints/authentication/cert_auth.cpp
  src/js/extensions/ccf/request.cpp
  tests/e2e_logging.py
  tests/npm-app/app.json
  tests/npm-app/src/endpoints/auth.ts
Labels: auto-backport, 5.x-todo

#6615 [release/5.x] Cherry pick: Any cert authn policy (#6608)
  CHANGELOG.md
  doc/build_apps/api.rst
  doc/build_apps/js_app_bundle.rst
  include/ccf/common_auth_policies.h
  include/ccf/endpoint.h
  include/ccf/endpoints/authentication/cert_auth.h
  include/ccf/endpoints/authentication/js.h
  js/ccf-app/src/endpoints.ts
  samples/apps/logging/js/app.json
  samples/apps/logging/js/src/logging.js
  samples/apps/logging/logging.cpp
  src/endpoints/authentication/cert_auth.cpp
  src/js/extensions/ccf/request.cpp
  tests/e2e_logging.py
  tests/npm-app/app.json
  tests/npm-app/src/endpoints/auth.ts
Labels: 5.x-backport

#6621 Update UVM endorsements test with fresh endorsements from C-AKS
  src/node/test/endorsements.cpp
  src/node/uvm_endorsements.h
  tests/uvm_endorsements/ecdsa_test1.cose
Labels: run-long-test

#6627 Delay lock taking slightly
  src/node/history.h
Labels: 5.x-todo, run-long-test

#6631 Remove deprecated fields
  src/node/node_state.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
Labels: run-long-test

#6633 Take `version_lock` when creating reserved Tx
  src/kv/store.h
Labels: 5.x-todo, run-long-test

#6634 Schema support for std::unordered_set
  CHANGELOG.md
  include/ccf/ds/json_schema.h
  include/ccf/ds/openapi.h
  src/ds/test/openapi.cpp
Labels: auto-backport, 5.x-todo

#6632 Compatibility for cose_signatures_config field in /join response
  src/node/rpc/cose_signatures_config.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
Labels: auto-backport, 5.x-todo

#6641 Increase number of writes in concurrency test to ensure conflict
  src/kv/test/kv_contention.cpp
Labels: auto-backport, 5.x-todo

#6642 [release/5.x] Cherry pick: Compatibility for cose_signatures_config field in /join response (#6632)
  src/node/rpc/cose_signatures_config.h
  src/node/rpc/node_call_types.h
  src/node/rpc/node_frontend.h
  src/node/rpc/serialization.h
Labels: 5.x-backport

#6637 Add issuer and subject to COSE signatures
  CHANGELOG.md
  cddl/ccf-merkle-tree-cose-signature.cddl
  cddl/ccf-receipt.cddl
  doc/host_config_schema/cchost_config.json
  include/ccf/node/cose_signatures_config.h
  include/ccf/node/startup_config.h
  python/src/ccf/cose.py
  samples/config/start_config.json
  src/common/configuration.h
  src/crypto/openssl/cose_sign.h
  src/host/configuration.h
  src/host/main.cpp
  src/kv/kv_types.h
  src/node/history.h
  src/node/identity.h
  src/node/node_state.h
  src/node/rpc/node_call_types.h
  src/node/rpc/test/frontend_test_infra.h
  src/node/test/historical_queries.cpp
  src/node/test/history.cpp
  src/node/test/snapshot.cpp
  tests/config.jinja
  tests/e2e_logging.py
  tests/e2e_operations.py
  tests/infra/remote.py
Labels: run-long-test

#6620 Azure Linux: tweak dataclass for compatibility with python 3.12
  tests/infra/interfaces.py
Labels: mariner

#6591 Enable unit tests for Azure Linux in CI
  .github/workflows/ci.yml
Labels: run-long-test, mariner

#6648 Support BIO read/write retries in OpenSSL 3.3
  src/enclave/tls_session.h
Labels: run-long-test, mariner

#6660 When joining, always retrieve the service's `subject_name` from the given cert
  CHANGELOG.md
  python/pyproject.toml
  src/node/identity.h
  tests/lts_compatibility.py
Labels: auto-backport, 5.x-todo

#6665 [release/5.x] Cherry pick: When joining, always retrieve the service's `subject_name` from the given cert (#6660)
  CHANGELOG.md
  src/node/identity.h
  tests/lts_compatibility.py
Labels: 5.x-backport

#6662 Extend pathlen for CAs
  CHANGELOG.md
  src/crypto/openssl/key_pair.cpp
  src/crypto/test/crypto.cpp
  tests/e2e_logging.py
Labels: auto-backport, 5.x-todo, run-long-test

#6663 [release/5.x] Cherry pick: Schema support for std::unordered_set (#6634)
  CHANGELOG.md
  include/ccf/ds/json_schema.h
  include/ccf/ds/openapi.h
  src/ds/test/openapi.cpp
Labels: 5.x-backport

#6667 [release/5.x] Cherry pick: Extend pathlen for CAs (#6662)
  CHANGELOG.md
  src/crypto/openssl/key_pair.cpp
  src/crypto/test/crypto.cpp
  tests/e2e_logging.py
Labels: 5.x-backport

#6671 Open `.committed` files read-only
  src/host/ledger.h
Labels: run-long-test
