Repository microsoft/CCF, pull requests merged in 2025-09, with the labels that each got.

#7245 AB perf test
  .github/workflows/bencher-ab.yml
  scripts/compare_bencher_ab.py
Labels: bench-ab

#7256 Log initial node attestation
  CHANGELOG.md
  src/node/node_state.h
Labels: auto-backport, 6.x-todo

#7261 Log initial node attestation (#7256)
  CHANGELOG.md
  python/pyproject.toml
  src/node/node_state.h
Labels: 6.x-backport

#7251 Put sha256 context init/shutdown under a RAII wrapper
  CHANGELOG.md
  include/ccf/crypto/openssl_init.h
  src/crypto/openssl/hash.cpp
  src/crypto/test/bench.cpp
  src/crypto/test/crypto.cpp
  src/enclave/enclave.h
  src/host/run.cpp
  src/host/test/ledger.cpp
  src/indexing/test/indexing.cpp
  src/kv/test/kv_bench.cpp
  src/kv/test/kv_contention.cpp
  src/kv/test/kv_test.cpp
  src/node/rpc/test/frontend_test.cpp
  src/node/rpc/test/node_frontend_test.cpp
  src/node/test/encryptor.cpp
  src/node/test/endorsements.cpp
  src/node/test/historical_queries.cpp
  src/node/test/history.cpp
  src/node/test/history_bench.cpp
  src/node/test/merkle_bench.cpp
  src/node/test/merkle_test.cpp
  src/node/test/receipt.cpp
  src/node/test/snapshot.cpp
  src/node/test/snapshotter.cpp
  src/pal/test/snp_attestation_validation.cpp
  src/pal/test/snp_ioctl_test.cpp
  tests/perf-system/submitter/submit.cpp
Labels: run-long-test, bench-ab

#7286 Cherry-pick #7240 to 6.x LTS
  CHANGELOG.md
  CMakeLists.txt
  include/ccf/pal/attestation.h
  include/ccf/pal/attestation_sev_snp.h
  python/pyproject.toml
  src/pal/attestation.cpp
  src/pal/test/attestation.h
  src/pal/test/snp_attestation_validation.cpp
  tests/npm_tests.py
Labels: 6.x-backport

#7293 [release/6.x] Port curlm to 6.x (#7103, #7102, #7219, #7213)
  CHANGELOG.md
  CMakeLists.txt
  cmake/common.cmake
  include/ccf/pal/attestation_sev_snp.h
  include/ccf/pal/attestation_sev_snp_endorsements.h
  include/ccf/service/tables/jsengine.h
  src/common/configuration.h
  src/enclave/main.cpp
  src/host/main.cpp
  src/host/proxy.h
  src/http/curl.h
  src/http/test/curl_test.cpp
  src/node/quote_endorsements_client.h
  src/pal/test/snp_attestation_validation.cpp
  src/snapshots/fetch.h
  tests/e2e_curl.py
  tests/infra/network.py
  tests/js-custom-authorization/custom_authorization.py
  tests/reconfiguration.py
  tests/requirements.txt
Labels: 6.x-backport

#7313 [release/6.x] Backport logging of digests of snapshot files #7300
  CHANGELOG.md
  python/pyproject.toml
  src/host/main.cpp
  src/snapshots/snapshot_manager.h
Labels: 6.x-backport

#7317 Retries for fetching snapshots
  CHANGELOG.md
  doc/host_config_schema/cchost_config.json
  src/host/configuration.h
  src/host/run.cpp
  src/snapshots/fetch.h
  tests/e2e_operations.py
  tests/infra/network.py
Labels: auto-backport, 6.x-todo

#7322 [release/6.x] Cherry pick: Remove pyopenssl (#7297)
  CHANGELOG.md
  python/src/ccf/receipt.py
  tests/e2e_logging.py
  tests/recovery.py
  tests/requirements.txt
Labels: 6.x-backport
