Repository microsoft/CCF, pull requests merged in 2025-02, with the labels that each got.

#6800 Load OpenSSL error strings
  src/crypto/openssl/openssl_wrappers.h
Labels: run-long-test

#6809 When computing virtual attestation, digest incrementally rather than slurping the entire package into memory
  src/pal/quote_generation.h
Labels: run-long-test

#6818 Handle multiple certificates in JWT CA bundle correctly
  CHANGELOG.md
  python/pyproject.toml
  src/node/jwt_key_auto_refresh.h
  src/tls/ca.h
  tests/jwt_test.py
Labels: auto-backport, 5.x-todo

#6810 Developing for Azure Linux easily
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post_create_setup.sh
  .github/workflows/ci.yml
  .github/workflows/long-test.yml
  .github/workflows/release.yml
  scripts/install-azure-linux-deps.sh
  scripts/install-azure-linux-extended.sh
  scripts/setup-ci.sh
  scripts/setup-dev.sh
Labels: run-long-test

#6819 [release/5.x] Cherry pick: Handle multiple certificates in JWT CA bundle correctly (#6818)
  CHANGELOG.md
  src/node/jwt_key_auto_refresh.h
  src/tls/ca.h
  tests/jwt_test.py
Labels: 5.x-backport

#6833 Select newest clang be default
  .github/workflows/ci.yml
  .github/workflows/long-test.yml
  .github/workflows/release.yml
  cmake/preproject.cmake
Labels: run-long-test

#6839 [release/5.x] Cherry-pick: Fix multi-threaded access to non-TLS servers (eg - SNP nodes fetching endorsements from THIM) (#6836)
  .snpcc_canary
  CHANGELOG.md
  src/enclave/session.h
  src/http/http2_session.h
  src/http/http_session.h
  src/node/quote_endorsements_client.h
Labels: 5.x-backport

#6842 [release/5.x] Cherry pick: Enable redirection when starting a network (#6732) | Fixed the backup redirection config in the start_network.py (#6755)
  tests/start_network.py
Labels: 5.x-backport

#6841 Support v3 SNP attestations
  include/ccf/pal/attestation.h
  include/ccf/pal/attestation_sev_snp.h
Labels: auto-backport, 5.x-todo

#6844 [release/5.x] Cherry pick: Support v3 SNP attestations (#6841)
  include/ccf/pal/attestation.h
  include/ccf/pal/attestation_sev_snp.h
Labels: 5.x-backport

#6836 Fix multi-threaded access to non-TLS servers (eg - SNP nodes fetching endorsements from THIM)
  .snpcc_canary
  CHANGELOG.md
  python/pyproject.toml
  src/enclave/session.h
  src/node/quote_endorsements_client.h
Labels: 5.x-todo

#6845 Fix pctx leak with RAII wrapper
  CHANGELOG.md
  src/crypto/openssl/public_key.cpp
Labels: auto-backport, 5.x-todo

#6846 [release/5.x] Cherry pick: Fix pctx leak with RAII wrapper (#6845)
  CHANGELOG.md
  src/crypto/openssl/public_key.cpp
Labels: 5.x-backport

#6852 Add `client_protocols` test to long-test job, and different golden file on Azure Linux
  .github/workflows/long-test.yml
  tests/client_protocols.py
  tests/tls_report_azure_linux.csv
Labels: run-long-test

#6849 Correct node membership condition
  CHANGELOG.md
  python/pyproject.toml
  python/src/ccf/ledger.py
Labels: auto-backport, 5.x-todo

#6857 [release/5.x] Cherry pick: Correct node membership condition (#6849)
  CHANGELOG.md
  python/src/ccf/ledger.py
Labels: 5.x-backport

#6835 Enable TSAN/ASAN on AL in CI
  .github/workflows/long-test.yml
  scripts/setup-ci.sh
  tests/acme_endorsement.py
  tests/npm_tests.py
Labels: run-long-test

#6863 Update the enclave dispatcher thread to wait on a condition variable for incoming writes
  CHANGELOG.md
  CMakeLists.txt
  src/ds/notifying.h
  src/ds/test/work_beacon.cpp
  src/ds/work_beacon.h
  src/enclave/enclave.h
  src/enclave/main.cpp
  src/enclave/virtual_enclave.h
  src/host/enclave.h
  src/host/main.cpp
Labels: run-long-test

#6866 Fix potential data race: Lock all KV maps during `apply_changes`, even those which are read-only
  src/kv/apply_changes.h
Labels: run-long-test
