Repository microsoft/CCF, pull requests merged in 2025-08, with the labels that each got.

#7173 Fix long tests: Forbid SAN or TSAN alongside snmalloc
  .github/workflows/long-test.yml
  CMakeLists.txt
Labels: run-long-test

#7171 Compatibility with TypeScript 5.9
  CHANGELOG.md
  js/ccf-app/package.json
  js/ccf-app/src/converters.ts
  js/ccf-app/src/polyfill.ts
  js/ccf-app/src/utils.ts
  js/ccf-app/test/polyfill.test.ts
  js/ccf-app/test/utils.test.ts
  tests/js-interpreter-reuse/package.json
  tests/npm-app/package.json
  tests/npm-app/src/endpoints/crypto.ts
  tests/npm-app/src/endpoints/snp_attestation.ts
Labels: auto-backport, 6.x-todo

#7185 [release/6.x] Cherry pick: Compatibility with TypeScript 5.9 (#7171)
  js/ccf-app/package.json
  js/ccf-app/src/converters.ts
  js/ccf-app/src/polyfill.ts
  js/ccf-app/src/utils.ts
  js/ccf-app/test/polyfill.test.ts
  js/ccf-app/test/utils.test.ts
  tests/js-interpreter-reuse/package.json
  tests/npm-app/package.json
  tests/npm-app/src/endpoints/crypto.ts
  tests/npm-app/src/endpoints/snp_attestation.ts
Labels: 6.x-backport

#7183 [release/6.x] Cherry pick: Add `keyUsage` extension to CA x509s (#7134)
  src/crypto/openssl/key_pair.cpp
  tests/client_protocols.py
  tests/tls_report_azure_linux.csv
Labels: 6.x-backport

#7212 Fix commit/rollback race on last_replicated
  src/kv/store.h
Labels: run-long-test
