Repository microsoft/CCF, pull requests merged in 2025-05, with the labels that each got.

#6999 Harden disaster recovery: Ignore duplicate sealed secrets
  CHANGELOG.md
  src/node/share_manager.h
  tests/recovery.py
  tests/testdata/double_sealed_service/common/member0_cert.pem
  tests/testdata/double_sealed_service/common/member0_enc_privk.pem
  tests/testdata/double_sealed_service/common/member0_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member0_privk.pem
  tests/testdata/double_sealed_service/common/member1_cert.pem
  tests/testdata/double_sealed_service/common/member1_enc_privk.pem
  tests/testdata/double_sealed_service/common/member1_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member1_privk.pem
  tests/testdata/double_sealed_service/common/member2_cert.pem
  tests/testdata/double_sealed_service/common/member2_enc_privk.pem
  tests/testdata/double_sealed_service/common/member2_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member2_privk.pem
  tests/testdata/double_sealed_service/common/service_cert.pem
  tests/testdata/double_sealed_service/common/user0_cert.pem
  tests/testdata/double_sealed_service/common/user0_privk.pem
  tests/testdata/double_sealed_service/ledger/ledger_1-2.committed
  tests/testdata/double_sealed_service/ledger/ledger_105-125.committed
  tests/testdata/double_sealed_service/ledger/ledger_126-145.committed
  tests/testdata/double_sealed_service/ledger/ledger_146-165.committed
  tests/testdata/double_sealed_service/ledger/ledger_166-186.committed
  tests/testdata/double_sealed_service/ledger/ledger_17-19.committed
  tests/testdata/double_sealed_service/ledger/ledger_187-206.committed
  tests/testdata/double_sealed_service/ledger/ledger_20-21.committed
  tests/testdata/double_sealed_service/ledger/ledger_207-227.committed
  tests/testdata/double_sealed_service/ledger/ledger_22-43.committed
  tests/testdata/double_sealed_service/ledger/ledger_228-247.committed
  tests/testdata/double_sealed_service/ledger/ledger_248-267.committed
  tests/testdata/double_sealed_service/ledger/ledger_268-288.committed
  tests/testdata/double_sealed_service/ledger/ledger_289-308.committed
  tests/testdata/double_sealed_service/ledger/ledger_3-16.committed
  tests/testdata/double_sealed_service/ledger/ledger_309-329.committed
  tests/testdata/double_sealed_service/ledger/ledger_330-349.committed
  tests/testdata/double_sealed_service/ledger/ledger_350-370.committed
  tests/testdata/double_sealed_service/ledger/ledger_371-390.committed
  tests/testdata/double_sealed_service/ledger/ledger_391-411.committed
  tests/testdata/double_sealed_service/ledger/ledger_412-431.committed
  tests/testdata/double_sealed_service/ledger/ledger_432-451.committed
  tests/testdata/double_sealed_service/ledger/ledger_44-64.committed
  tests/testdata/double_sealed_service/ledger/ledger_452-473.committed
  tests/testdata/double_sealed_service/ledger/ledger_474-483.committed
  tests/testdata/double_sealed_service/ledger/ledger_484-485.committed
  tests/testdata/double_sealed_service/ledger/ledger_486-491.committed
  tests/testdata/double_sealed_service/ledger/ledger_492-499.committed
  tests/testdata/double_sealed_service/ledger/ledger_500-502.committed
  tests/testdata/double_sealed_service/ledger/ledger_503-505.committed
  tests/testdata/double_sealed_service/ledger/ledger_506
  tests/testdata/double_sealed_service/ledger/ledger_65-84.committed
  tests/testdata/double_sealed_service/ledger/ledger_85-104.committed
  tests/testdata/double_sealed_service/snapshots/.gitkeep
Labels: auto-backport, 5.x-todo

#7001 [release/5.x] Cherry pick: Harden disaster recovery: Ignore duplicate sealed secrets (#6999)
  CHANGELOG.md
  src/kv/deserialise.h
  src/kv/kv_types.h
  src/node/history.h
  src/node/share_manager.h
  tests/recovery.py
  tests/testdata/double_sealed_service/common/member0_cert.pem
  tests/testdata/double_sealed_service/common/member0_enc_privk.pem
  tests/testdata/double_sealed_service/common/member0_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member0_privk.pem
  tests/testdata/double_sealed_service/common/member1_cert.pem
  tests/testdata/double_sealed_service/common/member1_enc_privk.pem
  tests/testdata/double_sealed_service/common/member1_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member1_privk.pem
  tests/testdata/double_sealed_service/common/member2_cert.pem
  tests/testdata/double_sealed_service/common/member2_enc_privk.pem
  tests/testdata/double_sealed_service/common/member2_enc_pubk.pem
  tests/testdata/double_sealed_service/common/member2_privk.pem
  tests/testdata/double_sealed_service/common/service_cert.pem
  tests/testdata/double_sealed_service/common/user0_cert.pem
  tests/testdata/double_sealed_service/common/user0_privk.pem
  tests/testdata/double_sealed_service/ledger/ledger_1-2.committed
  tests/testdata/double_sealed_service/ledger/ledger_105-125.committed
  tests/testdata/double_sealed_service/ledger/ledger_126-145.committed
  tests/testdata/double_sealed_service/ledger/ledger_146-165.committed
  tests/testdata/double_sealed_service/ledger/ledger_166-186.committed
  tests/testdata/double_sealed_service/ledger/ledger_17-19.committed
  tests/testdata/double_sealed_service/ledger/ledger_187-206.committed
  tests/testdata/double_sealed_service/ledger/ledger_20-21.committed
  tests/testdata/double_sealed_service/ledger/ledger_207-227.committed
  tests/testdata/double_sealed_service/ledger/ledger_22-43.committed
  tests/testdata/double_sealed_service/ledger/ledger_228-247.committed
  tests/testdata/double_sealed_service/ledger/ledger_248-267.committed
  tests/testdata/double_sealed_service/ledger/ledger_268-288.committed
  tests/testdata/double_sealed_service/ledger/ledger_289-308.committed
  tests/testdata/double_sealed_service/ledger/ledger_3-16.committed
  tests/testdata/double_sealed_service/ledger/ledger_309-329.committed
  tests/testdata/double_sealed_service/ledger/ledger_330-349.committed
  tests/testdata/double_sealed_service/ledger/ledger_350-370.committed
  tests/testdata/double_sealed_service/ledger/ledger_371-390.committed
  tests/testdata/double_sealed_service/ledger/ledger_391-411.committed
  tests/testdata/double_sealed_service/ledger/ledger_412-431.committed
  tests/testdata/double_sealed_service/ledger/ledger_432-451.committed
  tests/testdata/double_sealed_service/ledger/ledger_44-64.committed
  tests/testdata/double_sealed_service/ledger/ledger_452-473.committed
  tests/testdata/double_sealed_service/ledger/ledger_474-483.committed
  tests/testdata/double_sealed_service/ledger/ledger_484-485.committed
  tests/testdata/double_sealed_service/ledger/ledger_486-491.committed
  tests/testdata/double_sealed_service/ledger/ledger_492-499.committed
  tests/testdata/double_sealed_service/ledger/ledger_500-502.committed
  tests/testdata/double_sealed_service/ledger/ledger_503-505.committed
  tests/testdata/double_sealed_service/ledger/ledger_506
  tests/testdata/double_sealed_service/ledger/ledger_65-84.committed
  tests/testdata/double_sealed_service/ledger/ledger_85-104.committed
  tests/testdata/double_sealed_service/snapshots/.gitkeep
Labels: 5.x-backport

#7005 Fix typo mistake - commmitted to committed
  tla/consensus/ccfraft.tla
Labels: run-long-verification

#7010 Harden cross-version join: Handle non-monotonicity of presence of COSE signatures
  src/kv/deserialise.h
  src/kv/kv_types.h
  src/node/history.h
  tests/recovery.py
  tests/testdata/cose_flipflop_service/common/member0_cert.pem
  tests/testdata/cose_flipflop_service/common/member0_enc_privk.pem
  tests/testdata/cose_flipflop_service/common/member0_enc_pubk.pem
  tests/testdata/cose_flipflop_service/common/member0_privk.pem
  tests/testdata/cose_flipflop_service/common/service_cert.pem
  tests/testdata/cose_flipflop_service/common/user0_cert.pem
  tests/testdata/cose_flipflop_service/common/user0_privk.pem
  tests/testdata/cose_flipflop_service/ledger/ledger_1-14.committed
  tests/testdata/cose_flipflop_service/ledger/ledger_15-46.committed
  tests/testdata/cose_flipflop_service/snapshots/.gitkeep
Labels: auto-backport, 5.x-todo
