Repository microsoft/CCF, pull requests merged in 2025-03, with the labels that each got.

#6882 Take lock over `Snapshotter` state during callback
  src/node/snapshotter.h
Labels: run-long-test

#6884 TLA CI on Azure Linux
  .github/workflows/ci-verification.yml
  .github/workflows/long-verification.yml
Labels: run-long-verification

#6885 [release/5.x] Cherry pick: Don't throw error if the ledger directory exists but is empty on node start (#6859)
  src/host/main.cpp
  src/host/snapshots.h
  tests/e2e_operations.py
  tests/infra/network.py
Labels: 5.x-backport

#6902 Re-enable indexing test
  CMakeLists.txt
  src/consensus/aft/test/logging_stub.h
  src/indexing/test/indexing.cpp
Labels: run-long-test

#6913 [release/5.x] Cherry pick: Prevent racey access to indexer state (#6886)
  include/ccf/indexing/indexer_interface.h
  include/ccf/indexing/strategy.h
  src/indexing/indexer.h
Labels: 5.x-backport

#6914 Avoid a possible race condition
  src/node/node_state.h
Labels: run-long-test

#6921 [release/5.x] Update 5.x CHANGELOG
  CHANGELOG.md
Labels: 5.x-backport

#6912 Consolidate single execution path for `begin_private_recovery()`
  src/node/node_state.h
  src/node/secret_broadcast.h
  src/service/internal_tables_access.h
  src/service/tables/secrets.h
Labels: run-long-test

#6920 Test mid-recovery election
  CMakeLists.txt
  src/node/node_state.h
  tests/infra/node.py
  tests/infra/remote.py
  tests/recovery.py
Labels: run-long-test

#6931 Another attempt to fix the LTS test
  tests/infra/github.py
Labels: run-long-test

#6929 Remove ADO SNPCC job, superseded by GHA C-ACI job in main ci.yml
  .azure-pipelines-templates/azure_cli.yml
  .azure-pipelines-templates/build-ci-container.yml
  .azure-pipelines-templates/cg.yml
  .azure-pipelines-templates/checks.yml
  .azure-pipelines-templates/cmake.yml
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/configure.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines-templates/generate_ssh_key.yml
  .azure-pipelines-templates/install_deb.yml
  .azure-pipelines-templates/install_extended_testing_tools.yml
  .azure-pipelines-templates/install_others.yml
  .azure-pipelines-templates/misc.yml
  .azure-pipelines-templates/ninja.yml
  .azure-pipelines-templates/platform.yml
  .azure-pipelines-templates/publish_compatibility_report.yml
  .azure-pipelines-templates/publish_sbom.yml
  .azure-pipelines-templates/publish_tls_report.yml
  .azure-pipelines-templates/release.yml
  .azure-pipelines-templates/scan_build.yml
  .azure-pipelines-templates/test.yml
  .azure_pipelines_snp.yml
  .snpcc_canary
  CMakeLists.txt
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
  scripts/azure_deployment/arm_template.py
  scripts/azure_deployment/escape_data.sh
  scripts/azure_deployment/requirements.txt
Labels: 5.x-todo

#6936 [release/5.x] Cherry pick: Remove ADO SNPCC job, superseded by GHA C-ACI job in main ci.yml (#6929)
  .azure-pipelines-templates/azure_cli.yml
  .azure-pipelines-templates/build-ci-container.yml
  .azure-pipelines-templates/build_check.yml
  .azure-pipelines-templates/cg.yml
  .azure-pipelines-templates/checks.yml
  .azure-pipelines-templates/cmake.yml
  .azure-pipelines-templates/common.yml
  .azure-pipelines-templates/configure.yml
  .azure-pipelines-templates/daily-matrix.yml
  .azure-pipelines-templates/deploy_aci.yml
  .azure-pipelines-templates/generate_ssh_key.yml
  .azure-pipelines-templates/install_deb.yml
  .azure-pipelines-templates/install_extended_testing_tools.yml
  .azure-pipelines-templates/install_others.yml
  .azure-pipelines-templates/install_ssh_key.yml
  .azure-pipelines-templates/misc.yml
  .azure-pipelines-templates/ninja.yml
  .azure-pipelines-templates/platform.yml
  .azure-pipelines-templates/publish_compatibility_report.yml
  .azure-pipelines-templates/publish_sbom.yml
  .azure-pipelines-templates/publish_tls_report.yml
  .azure-pipelines-templates/release-matrix.yaml
  .azure-pipelines-templates/release.yml
  .azure-pipelines-templates/scan_build.yml
  .azure-pipelines-templates/simulation.yml
  .azure-pipelines-templates/test.yml
  .azure-pipelines-templates/trace_validation.yml
  .azure_pipelines_snp.yml
  .snpcc_canary
  CMakeLists.txt
  docker/ccf_ci_built
  scripts/azure_deployment/arm_aci.py
  scripts/azure_deployment/arm_template.py
  scripts/azure_deployment/escape_data.sh
  scripts/azure_deployment/requirements.txt
Labels: 5.x-backport

#6926 Ensure that end-of-private-recovery service open transaction is written at-most-once
  CHANGELOG.md
  scripts/setup-ci.sh
  src/node/node_state.h
  tests/infra/network.py
  tests/partitions_test.py
Labels: 5.x-todo, run-long-test

#6948 [release/5.x] Cherry pick: Consolidate single execution path for `begin_private_recovery()` (#6912)
  src/node/node_state.h
  src/node/secret_broadcast.h
  src/service/internal_tables_access.h
  src/service/tables/secrets.h
Labels: 5.x-backport

#6941 Long test on Azure Linux only
  .github/workflows/long-test.yml
  scripts/scan-build.sh
Labels: run-long-test
